### ISSUE TITLE
opening html files slows down emacs

### ISSUE THREAD

**Issue by gdkrmr** [vspinu/polymode#102]
I am using `PM-Rmd` and every time compile the document, the resulting html file is opened in emacs and Emacs gets really slow until I close the buffer with the html file.

I suppose the reason is that the images are part of the html file as base64, which makes the html really large.

I see no reason why emacs should open the resulting html file at all. Is this standard behavior, or did I misconfigure something?

**Comment by vspinu** [comment]
I am aware of this problem. It's not only images, but huge js which is encoded in one line by Rmarkdown. Emacs is very bad at handling long lines. 

The solution would be to pen html files outside emacs with browse-url and have this configurable in a uniform and generic fashion. But I haven't had time to get to that yet. 

As this behavior is extremely inconvenient I will push a quick fix for now which will dispatch html pages to browser-url.

**Comment by gdkrmr** [comment]
opening files directly in the browser is probably the best solution.

**Comment by vspinu** [comment]
I have just done that. If it doesn't work for you please configure `browse-url-browser-function` according to your taste.
