### ISSUE TITLE
Polymode does not change to R mode

### ISSUE THREAD

**Issue by jabranham** [vspinu/polymode#105]
Hello - 

I'm trying to edit an Rmd file and polymode does not change to R mode. I get errors like this:

`(poly-lock-fontify-now 144 210) -> (nil 144 210 nil): Args out of range: 208, 211`

and it remains in markdown-mode. I don't think I'm doing anything too crazy when I load it up:

```
    (use-package polymode 
      :ensure t
      :mode
      ("\\.Snw" . poly-noweb+r-mode)
      ("\\.Rnw" . poly-noweb+r-mode)
      ("\\.Rmd" . poly-markdown+r-mode))
```

EDIT: 

Weirdly, `Rnw` files do switch between latex mode and R mode but still generate the same error...

**Comment by vspinu** [comment]
What version of emacs is this? Could you provide a small rmd example? 

I haven't seen such problems for a while already.

**Comment by jabranham** [comment]
I'm running emacs 24.5.1. My emacs config is [on github](https://github.com/jabranham/emacs/blob/master/emacs.org).

This happens with all Rmd files, for example: 


    ---
   title: example
   output: pdf_document
    ---
    
    ```{r mytab, fig.cap = "My scatter"}
    library(ggplot2)
    ggplot(mtcars, aes(mpg, wt)) + geom_point()
    ```
    
    This is a sentence.

**Comment by vspinu** [comment]
I have just tried with emacs 24.5.1 and I don't see it. Could you please try with the following initialization script

```el

(setq inhibit-splash-screen t
      path-to-ESS "~/VC/ESS/"
      test-file   "~/tmp/tmp.Rmd"
      ;; temporary dir for MELPA installs
      package-user-dir (expand-file-name "~/tmp/ELPA/")
      package-list '(markdown-mode polymode))

(require 'package)
(progn 

  (message "Loading from MELPA")
  
  (add-to-list 'package-archives
               '("melpa" . "http://melpa.org/packages/") t)

  (when (member "--refetch" command-line-args-left)
    (message "Re-fetching from MELPA")
    (delete-directory package-user-dir t))
  
  (package-initialize)

  ;; Fetch list of packages available
  (unless package-archive-contents
    (package-refresh-contents))

  ;; install the packages that are missing, if any
  (dolist (package package-list)
    (unless (package-installed-p package)
      (package-install package))))

(add-to-list 'load-path (concat path-to-ESS "lisp/"))
(load (concat path-to-ESS "lisp/ess-site.el"))

(add-to-list 'auto-mode-alist '("\\.Rmd" . poly-markdown+r-mode))
(find-file test-file)
```

Modify the header accordingly and run it with `emacs -q -l script.el`.

**Comment by jabranham** [comment]
Yes, then it works. 

Also, I've noticed that (using my config, not that script) if I start an R process then polymode will switch to R-mode inside the chunks.

**Comment by vspinu** [comment]
> I start an R process then polymode will switch to R-mode inside the chunks. 

Hm. That means something in your R config is relying on running R process. Would be nice to know what. 

I like your config, will spend some time going through it and picking up goodies here and there.  You don't have instructions of how to generate the actual init script. Is it simply `org-babel-tangle`?

**Comment by jabranham** [comment]
Thanks! The actual `init.el` file isn't super interesting but it's in the [repo](https://github.com/jabranham/emacs)

Oh, that's interesting. My `.Rprofile` isn't that complicated - just picking a CRAN mirror and telling R never to ask me if I want to save my workspace when I exit. I wouldn't think that these are that uncommon, so I'm a little surprised it causes trouble here:

`~/.Rprofile` :

```
local({
  r <- getOption("repos")
      r["CRAN"] <- "https://cloud.r-project.org/"
          options(repos = r)
})
utils::assignInNamespace(
    "q",
    function(save = "no", status = 0, runLast = TRUE)
    {
    .Internal(quit(save, status, runLast))
    },
"base"
)
```

**Comment by vspinu** [comment]
> but it's in the repo

Yes. That's what I meant. How do you get from the org file from your repo to actual .emacs.el file?

> Rprofile isn't that complicated 

Rprofile is probably irrelevant. Something in your R buffers that requires R process interferes with polymode. It might be completion, or lintr, or who knows what. Probably not on ESS end because I would have noticed by now.

**Comment by jabranham** [comment]
Ah, gotcha. `org-babel-load-file` tangles the org file and loads the resulting el file. It's near the bottom of `init.el`. 

I found the culprit. Below is how I load up ESS. The (now commented-out) keybinding to call ess-help was somehow stopping polymode from working properly. 

```emacs-lisp
    (use-package ess-site 
      :ensure ess
      :diminish eldoc-mode
      ;; :bind (:map ess-mode-map
      ;;             ("C-h h" . ess-help))
      :config
      (add-hook 'ess-mode-hook
                (lambda ()
                  (ess-set-style 'RStudio)))
      (setq ess-offset-arguments 'prev-line)
      (setq ess-ask-for-ess-directory nil)
      (setq ess-pdf-viewer-pref "emacsclient")
      (defun my/add-pipe ()
        "Adds a pipe operator %>% with one space to the left and then
    starts a newline with proper indentation"
        (interactive)
        (just-one-space 1)
        (insert "%>%")
        (ess-newline-and-indent))
      (define-key ess-mode-map (kbd "M-p") 'my/add-pipe))
```

**Comment by vspinu** [comment]
> he (now commented-out) keybinding to call ess-help was somehow stopping polymode from working properly. 

Hm. How could this be? I guess it might be `use-package` way of doing stuff. Will have to investigate.  Thanks for digging it up.

**Comment by jabranham** [comment]
OK, I have at least figured out a workaround.

The `:bind` call in the `use-package` declaration was deferring ESS from loading ([see here](https://github.com/jwiegley/use-package#binding-within-local-keymaps)). I can specify `:defer` [with an integer](https://github.com/jwiegley/use-package#defer-now-accepts-an-optional-integer-argument) to load ESS after `int` seconds of idle time. I've set it to 1 since ESS doesn't take long to load for me. 

Then when I open Rmd files with poly-mode this works just fine. 

I still don't understand, however, why `Rnw` files were totally unaffected by this.

Feel free to close this issue since it's pretty specific.
