### ISSUE TITLE
Error displaying output file: Wrong type argument: stringp, nil

### ISSUE THREAD

**Issue by Jehops** [vspinu/polymode#116]
Hi,

After running  `polymode-export`, when the resulting pdf is to be displayed, the error `Error while displaying ’summary[woven][exported].pdf’: Wrong type argument: stringp, nil` occurs.  Others may be seeing the same or similar errors (https://www.reddit.com/r/emacs/comments/54h7q8/i_keep_getting_wrong_type_argument_stringp_nil/).

**Comment by plantarum** [comment]
I think I found the problem. See #118

**Comment by vspinu** [comment]
Yes. That was the problem indeed. Thank you @plantarum!
