### ISSUE TITLE
Needed : exporters for XeLaTeX and LuaLaTex engines

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [vspinu/polymode#122]
The current exporters, use, as far as I can see, pdftex or latexmk for export to PDF. This is true at least for .Rnw files usong polt-noweb+R.

This is a problem when one has to use XeTeX or LuaLaTex (e. g. non-english texts, OTF fonts, etc...). At least latexmk can be directed to use XeTeX or LuaLaTeX by the -lualatex, -xetex or -pdflatex="lualatex" options.

This could be done automatically when AucTeX is used, by searching the value of AucTeX'sTex-engine configuration variable.

This enhancement could also be done by the addition of specialized exporters to poly-noweb.el.

**Comment by vspinu** [comment]
I have added these both as separate exporters and as export `to` options to `latexmk`. 

I can add automatic picking from auctex option but I would rather have a separate auctex exporter rather than mix things up.  

Thanks for bringing this up.

**Comment by EmmanuelCharpentier** [comment]
My god ! less than alfa a day between the initial remark and implementation. Now, that's responsiveness...

Thank you very much !

A separate exporter via AucTeX is also an *excellent* (even a great) idea. I didn't think of it, I volunteer to guinea-pig it...

**Comment by vspinu** [comment]
> Now, that's responsiveness...

Well. That's rather an exception. I haven't been using polymode for my work for more than a year now, and as a result the development was stagnating as well.
