### ISSUE TITLE
defmethod deprecated

### ISSUE THREAD

**Issue by paynito** [vspinu/polymode#125]
are you going to change to cl-defmethod?  or would that break polymode for users on emacs 24?

    polymode/polymode-classes.el: ‘defmethod’ is an obsolete macro (as of 25.1); use ‘cl-defmethod’ instead.
    polymode/polymode-classes.el: ‘defgeneric’ is an obsolete macro (as of 25.1); use ‘cl-defgeneric’ instead.

**Comment by vspinu** [comment]
Yes. Will have to change that sooner or later.
