### ISSUE TITLE
More elaborate headers in Markdown mode

### ISSUE THREAD

**Issue by pwl** [vspinu/polymode#126]
I tried to use `polymode` to edit Markdown files with more complex headers like this one https://github.com/mpastell/Weave.jl/blob/master/examples/gadfly_md_sample.jmd#L19 but it doesn't seem to catch the language right when there are other terms after a `;` in parenthesis.  The regex seems to catch `julia`, `{julia}` and `lang=julia` but not `{julia=lang}` or `{julia=lang; eval=false}`.  I don't know how standard this header format is though, so I don't know if it makes sense to include it in `polymode`.

**Comment by vspinu** [comment]
Do you mean `{lang=julia}`?   This should be caught by the regexp but it seems like this is not happening in emacs 25. As to `julia;` the `;` at the end messes the regexp up. 

I think besides the regexp a more extensive cleanup of mode names should be done internally as well.

**Comment by pwl** [comment]
It certainly doesn't recognize `{lang=julia}`, I'm using polymode `20161218.1326` and Emacs `25.1.1`.

**Comment by vspinu** [comment]
Should be fine now. Thanks!

**Comment by pwl** [comment]
Thanks for a quick fix!
