### ISSUE TITLE
C/C++ identifier is different between org and polymode 

### ISSUE THREAD

**Issue by xmao** [vspinu/polymode#127]
Thanks for creating polymode,  a really sweet package for editing source directly in orgmode!

An annoying thing is, orgmode uses C and C++ (upper case) while polymode uses c and c++ (lower case). Can you please make polymode consistent or give a comprised resolution?

**Comment by vspinu** [comment]
Thanks for pointing this out.

**Comment by xmao** [comment]
Thank you very much for quick response!
