### ISSUE TITLE
Compatability with persp-mode?

### ISSUE THREAD

**Issue by brendan-r** [vspinu/polymode#132]
Hello there,

Firstly, thank you for polymode!

I've recently been trying to use [`persp-mode`] with polymode/Rmarkdown. The idea is I can save the state of a project (window configurations, etc.), and then come back to it later.

However, only with Rmarkdown/polymode, when loading a perspective from a file, I encounter the error `Customize alist is not specified, nor  ess-local-customize-alist is set`. The file/perspective does not load. This does not occur with plain .R files.

This could well be a bug that is better reported in the `persp-mode` repo, but, any ideas about what might be going on?

[`persp-mode`]: https://github.com/Bad-ptr/persp-mode.el

**Comment by vspinu** [comment]
It's hard to say. The error is from ESS, but I guess it has to do with how perspective mode saves buffers. It might not take proper care of the indirect buffers that polymode is base on. Can you provide a backtrace?

**Comment by brendan-r** [comment]
I have stopped using `persp-mode` for unrelated reasons. Closing, sorry for the fuss!
