### ISSUE TITLE
Cannot find function ‘r-mode’, using ‘poly-fallback-mode’

### ISSUE THREAD

**Issue by idavydov** [vspinu/polymode#134]
I have GNU Emacs 25.2.2, ess 20170603.817 from melpa and polymode from git master (0340f5e7e55235832e59673f027cc79a23cbdcd6).

In my `~/.emacs` I have:

```
(add-to-list 'auto-mode-alist '("\\.Rmd" . poly-markdown+r-mode))
```

When I open an `.Rmd` file I get:

```
Cannot find function ‘r-mode’, using ‘poly-fallback-mode’ [72 times]
```

Any ideas on how to overcome this?

Thanks!

**UPD**:

1. This doesn't happen if I start an R process first.
2. I tried script from [here](https://github.com/vspinu/polymode/issues/105#issuecomment-240712956). In this case everything works properly.
3. I created a minimal .emacs file with which the problem reproduces:

```
(require 'package) 
(add-to-list 'package-archives
              '("melpa" . "https://melpa.org/packages/"))
(package-initialize) ;; You might already have this line
(setq load-path
      (append '("~/.emacs.d/polymode"  "~/.emacs.d/polymode/modes")
              load-path))
(require 'poly-R)
(require 'poly-markdown)
(add-to-list 'auto-mode-alist '("\\.md" . poly-markdown-mode))
(add-to-list 'auto-mode-alist '("\\.Snw" . poly-noweb+r-mode))
(add-to-list 'auto-mode-alist '("\\.Rnw" . poly-noweb+r-mode))
(add-to-list 'auto-mode-alist '("\\.Rmd" . poly-markdown+r-mode))
```

**Comment by vspinu** [comment]
This is ESS issue, r-mode is not auto-loaded, but R-mode is.

**Comment by vspinu** [comment]
Try this `(autoload 'r-mode "ess-site.el" "Major mode for editing R source." t)`

**Comment by idavydov** [comment]
This worked, thanks a lot!

**Comment by vspinu** [comment]
Fixed on ESS side. Thanks for bringing up.

**Comment by vspinu** [comment]
What is the markdown snippet you are  seeing this with? If you use ESS from git teh autoload is not necessary. There is an explict `(defalias 'r-mode #'R-mode)`.

And btw, this message is no longer in polymode next branch and you really (really!) want to use "next" branch. Master is non-functional.

**Comment by flies1** [comment]
Thanks for your rapid response!

Here's a dummy that reproduces: 

   # Description of this document

   This document provides an example 
   
   ```{ r echo =F}
   x<-runif(100)



Note that I get a different error message if the `{ r echo=F}` is replaced with `{r echo=F}` (no space)

**Comment by vspinu** [comment]
I see. There should be no space between the bracket and r.

**Comment by flies1** [comment]
Ok. I have re-cloned polymode from `next` branch (git clone --single-branch --branch next https://github.com/polymode/polymode.git ), and removed the erroneous space.

Now I see the error, "Polymode error (pm--mode-setup ’markdown-mode): Symbol’s function definition is void: markdown-mode", and I am in `Fundamental PM-Rmd` mode.

Should I create a new issue? (my git/github experience is limited, thanks for bearing with me)

**Comment by vspinu** [comment]
As the error suggests, you don't seem to have markdown mode loaded. ATM
poly-markdown doesn't explicitly require it but this will change very soon.
