### ISSUE TITLE
definition in article.cls?

### ISSUE THREAD

**Issue by slyrus** [vspinu/polymode#138]
Perhaps I'm doing something grossly wrong, but I can't run pdflatex on the tex file produced from minimal.Rnw. It seems my article.cls doesn't have the definitions/definition definitions (ugh...). If I replace the bit inside the begin/end document block with that from minimal.Snw it works fine.

**Comment by vspinu** [comment]
Oh. Those where intended for font-lock and indentation tests. But you are right, samples should work with the default exporters. Fixed.
