### ISSUE TITLE
how to match xml block

### ISSUE THREAD

**Issue by jilen** [vspinu/polymode#139]
```scala
object UI {

  @dom
  def render(spans: Vars[Int]) = {
    <div>
      <div>
        <span>
        </span>
     </div>
    </div>
  }
}
```
For above example how could I match the xml block to active the inner mode

**Comment by knu** [comment]
I think you could rely on the indent level, assuming the last `</div>` is aligned with the first `<div>`.  To match them, both `:head-reg` and `:tail-reg` have to be functions instead of regexps.

**Comment by jilen** [comment]
Thanks for you reply, I will give a try

**Comment by knu** [comment]
Check out my [poly-ruby-mode](https://github.com/knu/poly-ruby.el/blob/master/poly-ruby.el), it matches here document blocks in Ruby (`<<FOO`…`FOO`) and could be a useful reference.
