### ISSUE TITLE
Emacs init issue with polymode 20170307.322

### ISSUE THREAD

**Issue by llmorreale** [vspinu/polymode#143]
I get this error when trying to load emacs 25.2 with polymode:
Cannot open load file: No such file or directory, eieio-base

My init file calling polymode:
(add-to-list 'load-path "~/.emacs.d/elpa/polymode-20170307.322/")
(require 'poly-R)
(require 'poly-markdown)

I looked in the emacs/lisp/elisp folder and eieio-base.el exists, but it is not being recognized. Any help would be greatly appreciated.

**Comment by vspinu** [comment]
Most likely a compilation issue.  Try to delete that folder and all other polymode-YMD folders (if any) and re-install.

**Comment by vspinu** [comment]
I hope you fixed your issues. If not please re-open.
