### ISSUE TITLE
how to disable poly-org-mode

### ISSUE THREAD

**Issue by vapniks** [vspinu/polymode#148]
Hi Vitalie, first of all thanks for creating this great package. 
I only just discovered it, and it's just what I've been looking for since I often use `org-mode` for stats projects where I mix code with text, and it's very useful to be able to use the `ess` keybindings in the `org-mode` buffer.
However, I notice that there are still a few bugs to iron out, and I don't want it enabled all the time. 
How can I disable it? When I try `M-x poly-org-mode` a second time it does nothing, even if I use a prefix arg.

**Comment by vspinu** [comment]
How do you enable `poly-org-mode`? (it's not enabled by default). You should be able to `M-x org-mode` or `poly-org-mode` depending on what you want.

 Polymodes behave like major mode and don't understand `C-u ...` prefix.

**Comment by vapniks** [comment]
I open an .org file in which emacs automatically starts `org-mode`, and then I do `M-x poly-org-mode`
which turns on `poly-org` minor mode. I am able to turn off other minor modes by executing their respective commands, but that doesn't work with `poly-org-mode`.

**Comment by vspinu** [comment]
Then simply `M-x org-mode` should do the trick.

**Comment by vapniks** [comment]
Great, that works, thanks (don't know why I didn't think of it myself).
