### ISSUE TITLE
emacs loses local variables after mode change

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [vspinu/polymode#150]
Note : this bug report is **identical** to a bug report I posted to the ESS-bugs mailing list. I just confirmed that the issue I reported concerning `Rnw-mode` also affects `poly-noweb+R`. Therefore, the problem bught be on ESS's side, or a logic problem common to both ESS and `polymode` (wiich, ISTR, share at least one proeminent developer).

Edited copy of the ESS bug report begins : 

-----
I have prepared a minimal example and a minimal init file to illustrate 
the problem. To reproduce and follow the description (below), invoke : 

emacs -q -name "emacs init minimal" -l initMinimal.el Essai0.Rnw 

========== Minimal .Rnw file : Essai0.Rnw ========== 

\documentclass[a4paper]{article} 

<<KnitrSetup, echo=FALSE, results="hide">>= 
library(knitr) 
@ 

\usepackage[utf8]{inputenc} 
\usepackage[T1]{fontenc} 
\usepackage{newtxtext,newtxmath} 

\title{Test archi-minimale Rnw-mode + AUCTeX} 
\author{Emmanuel Charpentier} 
\date{2018/02/09} 

\begin{document} 

\maketitle 

<<FirstRChunk, echo=TRUE, results="markup">>= 
2+1 
@ 

\end{document} 

%%% Local Variables: 
%%% TeX-master: "Essai0" 
%%% TeX-engine: default 
%%% mode: poly-noweb+R 
%%% End: 

_Note : for testing the problem with `poly-noweb+R`, I just used my "normal" .init, which, among other things, contains a `(require 'polymode)` statement ensuring the availability of `poly-noweb+R`, and precious little else related toLaTeX/R/etc..._

========== Minimal .init file : initMinimal.el ========== 

;; initialisaton minimale pour débourrage ESS 

;; ESS 
(require 'server) 
(unless (server-running-p) (server-start)) 

;; AUCTeX 
(require 'tex) 
(require 'reftex) ;; reftex 

;; pdf-tools 
;; (require 'pdf-tools) ;; PDF tools (Oui +++) 

;; Utilitaires divers 
(global-set-key [f4] 'goto-line) ;; S'avère très utile 
(put 'downcase-region 'disabled nil) ;; idem 
(put 'upcase-region 'disabled nil) 
(put 'capitalize-region 'disabled nil) 

;; Visionneuse AUCTeX 
;; (setq Selection-visionneuse 
;; '(((output-dvi has-no-display-manager) 
;; "dvi2tty") 
;; ((output-dvi style-pstricks) 
;; "dvips and gv") 
;; (output-dvi "xdvi") 
;; (output-pdf "PDF Tools") 
;; ;; Alternative 
;; ;; (output-pdf "Evince") 
;; (output-html "xdg-open"))) 
;; AUCTeX 
(add-hook 'LaTeX-mode-hook 'turn-on-reftex) ; with AUCTeX LaTeX mode 
(add-hook 'latex-mode-hook 'turn-on-reftex) ; with Emacs latex mode 
(add-hook 'LaTeX-mode-hook 'visual-line-mode) ; ?? 
(add-hook 'TeX-after-compilation-finished-functions 
'TeX-revert-document-buffer) 

;; ESS 
(setq-default ess-dialect "R") 

;; PDF tools : 2016-12-16 : merdoie (ne termine pas)... Réglé. 
;; (pdf-tools-install) 

(custom-set-variables 
;; custom-set-variables was added by Custom. 
;; If you edit it by hand, you could mess it up, so be careful. 
;; Your init file should contain only one such instance. 
;; If there is more than one, they won't work right. 
'(TeX-PDF-mode t) 
'(TeX-auto-save t) 
'(TeX-command-extra-options "-shell-escape") 
'(TeX-file-extensions 
(quote 
("Rnw" "tex" "sty" "cls" "ltx" "texi" "txi" "texinfo" "dtx"))) 
'(TeX-parse-self t) 
'(TeX-source-correlate-method (quote synctex)) 
'(TeX-source-correlate-mode t) 
'(TeX-source-correlate-start-server t) 
;; '(TeX-view-program-selection Selection-visionneuse) 
'(default-frame-alist (quote ((top . 1) (left . 1) (width . 81) (height . 38)))) 
'(ess-help-own-frame (quote one)) 
;; '(ess-pdf-viewer-pref "emacsclient") 
'(ess-swv-plug-into-AUCTeX-p t) 
'(ess-swv-processor (quote knitr)) 
'(inferior-ess-same-window nil) 
'(initial-frame-alist (quote ((top . 1) (left . 1) (width . 81) (height . 38)))) 
'(package-selected-packages 
(quote 
(pdf-tools dash git-commit magit magit-popup with-editor auctex js2-mode zotelo stan-snippets pylint polymode pandoc-mode org markdown-mode geiser flycheck-pyflakes ess auto-complete-sage))) 
'(polymode-exporter-output-file-format "%s") 
'(polymode-weave-output-file-format "%s") 
'(reftex-file-extensions 
(quote 
(("tex" ".tex" ".ltx" ".Rnw" ".nw" ".Rmd") 
("bib" ".bib")))) 
'(reftex-plug-into-AUCTeX t) 
'(sage-shell-sagetex:auctex-command-name "LaTeX") 
'(sage-shell:use-prompt-toolkit t) 
'(show-paren-mode t)) 

========== Description of the problem ========== 

When this file is loaded in emacs, all is well : `M-n r` correctly knits 
Essai0.Rnw into Essai0.tex, `C-c C-c` correctly LaTeXes Essai0.tex into 
Essai0.pdf. 

However, after editing the `FirstRChunk` chunk (or even moving into it 
then out), emacs loses the local variables `TeX-master` and `TeX-engine`. 

Consequences : 

* `M-n r` still correctly knits Essai0.Rnw to Essai0.tex 

* `C-c C-c` tries to LaTeX Essai0.Rnw, which fails on line 3, since the 
beginning of the `KnitrSetup` chunk is taken to be ordinary text 
placed before `\begin{document}`, which is anathemous to LaTeX. 

* Similarly, when `TeX-engine` is initially set to luatex or xetex in 
the 'Local variables:' segment, this value is lost and `C-c C-c` invokes 
pdflatex. 

* Absent the "KnitrSetup" chunk, `C-c C-c` LaTeXes Essai0.Rnw into 
Essai0.pdf, where the text of the "FirstRChunk" appears as "normal" text. 

Resetting AUCTeX (with `C-u C-c C-n`) restores the expected behaviour. 

Hope this helps the understanding of the problem, 

-----

```
------------------------------------------------------- 
This bug report will be sent to the ESS bugs email list 
Press C-c C-c when you are ready to send your message. 
------------------------------------------------------- 
Finished setting up ESS-mode. 
ess-request-a-process: {beginning} 
(n-i-m-l: 1)(ess-setq-vars-LOCAL): language=S, dialect=R, buf=nil, comint..echoes=t, 
comint..sender=comint-simple-send 
(ess-mode-1): ess-language=S, ess-dialect=R buf=Essai0.Rnw 
(ess-mode-1.5): alist=((inferior-ess-reload-function quote inferior-ess-reload:R) (ess-quit-function quote ess-quit:R) (ess-send-region-function quote ess-send-region:R) (ess-load-file-function quote ess-load-file:R) (ess-build-load-command-function quote ess-build-load-command:R) (ess-build-eval-command-function quote ess-build-eval-command:R) (ess-local-customize-alist quote ess-r-customize-alist) (ess-dialect . R) (ess-suffix . R) (ess-ac-sources . ess-r-ac-sources) (ess-company-backends . ess-r-company-backends) (ess-build-tags-command . ess-r-build-tags-command) (ess-traceback-command . ess-r-traceback-command) (ess-call-stack-command . ess-r-call-stack-command) (ess-mode-completion-syntax-table . ess-r-completion-syntax-table) (ess-build-eval-message-function function ess-r-build-eval-message) (ess-format-eval-command-function function ess-r-format-eval-command) (ess-format-load-command-function function ess-r-format-load-command) (ess-send-region-function function ess-r-send-region) (ess-load-file-function function ess-r-load-file) (ess-make-source-refd-command-function function ess-r-make-source-refd-command) (ess-format-eval-message-function function ess-r-format-eval-message) (ess-install-library-function function ess-r-install-library) (ess-eldoc-function function ess-r-eldoc-function) (ess-help-web-search-command function ess-r-sos) (ess-build-help-command-function function ess-r-build-help-command) (ess-dump-filename-template . ess-r-dump-filename-template) (ess-mode-editing-alist . ess-r-editing-alist) (ess-change-sp-regexp . ess-r-change-sp-regexp) (ess-help-sec-regex . ess-help-r-sec-regex) (ess-help-sec-keys-alist . ess-help-r-sec-keys-alist) (ess-loop-timeout . ess-r-loop-timeout) (ess-function-pattern . ess-r-function-pattern) (ess-object-name-db-file . ess-r-namedb.el) (ess-smart-operators . ess-r-smart-operators) (inferior-ess-program . inferior-ess-r-program-name) (inferior-ess-objects-command . inferior-ess-r-objects-command) (inferior-ess-font-lock-keywords quote inferior-ess-r-font-lock-keywords) (inferior-ess-search-list-command . search() 
) (inferior-ess-help-command . inferior-ess-r-help-command) (inferior-ess-help-filetype) (inferior-ess-exit-command . q()) (inferior-ess-exit-prompt . Save workspace image? [y/n/c]: ) (inferior-ess-start-file) (inferior-ess-start-args . ) (ess-error-regexp-alist . ess-r-error-regexp-alist) (ess-describe-object-at-point-commands quote ess-r-describe-object-at-point-commands) (ess-STERM . iESS) (ess-editor . ess-r-editor) (ess-pager . ess-r-pager) (ess-mode-syntax-table . ess-r-syntax-table) (font-lock-syntactic-face-function function ess-r-font-lock-syntactic-face-function) (prettify-symbols-alist quote ((<- . 8592) (<<- . 8606) (-> . 8594) (->> . 8608))) (ess-language . S) (inferior-ess-exit-command . q() 
) (inferior-ess-language-start eval inferior-S-language-start) (comint-use-prompt-regexp . t) (comint-process-echoes . t) (inferior-ess-primary-prompt . > ) (inferior-ess-secondary-prompt . + ) (comment-start . #) (ess-imenu-generic-expression . ess-imenu-S-generic-expression) (comment-add . 1) (comment-start-skip . #+ *) (comment-use-syntax . t) (comment-column . 40) (ess-no-skip-regexp concat ^ *@\| (default-value (quote ess-no-skip-regexp))) (inferior-ess-prompt . inferior-S-prompt) (ess-get-help-topics-function function ess-s-get-help-topics-function) (ess-getwd-command . getwd() 
) (ess-setwd-command . setwd('%s') 
) (ess-funargs-command . .ess_funargs("%s") 
) (fill-nobreak-predicate quote ess-inside-string-p) (normal-auto-fill-function quote ess-do-auto-fill) (ess-execute-screen-options-command . options(width=%d, length=99999) 
)) 
(ess-mode-1.6): editing-alist=((paragraph-start concat \s-*$\| page-delimiter) (paragraph-separate concat \s-*$\| page-delimiter) (paragraph-ignore-fill-prefix . t) (require-final-newline . mode-require-final-newline) (indent-line-function quote ess-indent-line) (parse-sexp-ignore-comments . t) (ess-style . ess-default-style) (ess-mode-syntax-table . ess-r-syntax-table) (add-log-current-defun-header-regexp . ^\(.+\)\s-+<-[ 
]*function) (ess-font-lock-keywords quote ess-R-font-lock-keywords) (ess-font-lock-defaults ess--extract-default-fl-keywords ess-R-font-lock-keywords) (font-lock-defaults quote (ess-font-lock-defaults nil nil ((46 . w) (95 . w))))) 
(ess-setq-vars-LOCAL): language=S, dialect=R, buf=nil, comint..echoes=t, comint..sender=comint-simple-send 

Finished setting up ESS-mode. 
(n-i-m-l: 1)(ess-setq-vars-LOCAL): language=S, dialect=R, buf=nil, comint..echoes=t, comint..sender=comint-simple-send 
(ess-mode-1): ess-language=S, ess-dialect=R buf=Essai0.Rnw 
(ess-mode-1.5): alist=((inferior-ess-reload-function quote inferior-ess-reload:R) (ess-quit-function quote ess-quit:R) (ess-send-region-function quote ess-send-region:R) (ess-load-file-function quote ess-load-file:R) (ess-build-load-command-function quote ess-build-load-command:R) (ess-build-eval-command-function quote ess-build-eval-command:R) (ess-local-customize-alist quote ess-r-customize-alist) (ess-dialect . R) (ess-suffix . R) (ess-ac-sources . ess-r-ac-sources) (ess-company-backends . ess-r-company-backends) (ess-build-tags-command . ess-r-build-tags-command) (ess-traceback-command . ess-r-traceback-command) (ess-call-stack-command . ess-r-call-stack-command) (ess-mode-completion-syntax-table . ess-r-completion-syntax-table) (ess-build-eval-message-function function ess-r-build-eval-message) (ess-format-eval-command-function function ess-r-format-eval-command) (ess-format-load-command-function function ess-r-format-load-command) (ess-send-region-function function ess-r-send-region) (ess-load-file-function function ess-r-load-file) (ess-make-source-refd-command-function function ess-r-make-source-refd-command) (ess-format-eval-message-function function ess-r-format-eval-message) (ess-install-library-function function ess-r-install-library) (ess-eldoc-function function ess-r-eldoc-function) (ess-help-web-search-command function ess-r-sos) (ess-build-help-command-function function ess-r-build-help-command) (ess-dump-filename-template . ess-r-dump-filename-template) (ess-mode-editing-alist . ess-r-editing-alist) (ess-change-sp-regexp . ess-r-change-sp-regexp) (ess-help-sec-regex . ess-help-r-sec-regex) (ess-help-sec-keys-alist . ess-help-r-sec-keys-alist) (ess-loop-timeout . ess-r-loop-timeout) (ess-function-pattern . ess-r-function-pattern) (ess-object-name-db-file . ess-r-namedb.el) (ess-smart-operators . ess-r-smart-operators) (inferior-ess-program . inferior-ess-r-program-name) (inferior-ess-objects-command . inferior-ess-r-objects-command) (inferior-ess-font-lock-keywords quote inferior-ess-r-font-lock-keywords) (inferior-ess-search-list-command . search() 
) (inferior-ess-help-command . inferior-ess-r-help-command) (inferior-ess-help-filetype) (inferior-ess-exit-command . q()) (inferior-ess-exit-prompt . Save workspace image? [y/n/c]: ) (inferior-ess-start-file) (inferior-ess-start-args . ) (ess-error-regexp-alist . ess-r-error-regexp-alist) (ess-describe-object-at-point-commands quote ess-r-describe-object-at-point-commands) (ess-STERM . iESS) (ess-editor . ess-r-editor) (ess-pager . ess-r-pager) (ess-mode-syntax-table . ess-r-syntax-table) (font-lock-syntactic-face-function function ess-r-font-lock-syntactic-face-function) (prettify-symbols-alist quote ((<- . 8592) (<<- . 8606) (-> . 8594) (->> . 8608))) (ess-language . S) (inferior-ess-exit-command . q() 
) (inferior-ess-language-start eval inferior-S-language-start) (comint-use-prompt-regexp . t) (comint-process-echoes . t) (inferior-ess-primary-prompt . > ) (inferior-ess-secondary-prompt . + ) (comment-start . #) (ess-imenu-generic-expression . ess-imenu-S-generic-expression) (comment-add . 1) (comment-start-skip . #+ *) (comment-use-syntax . t) (comment-column . 40) (ess-no-skip-regexp concat ^ *@\| (default-value (quote ess-no-skip-regexp))) (inferior-ess-prompt . inferior-S-prompt) (ess-get-help-topics-function function ess-s-get-help-topics-function) (ess-getwd-command . getwd() 
) (ess-setwd-command . setwd('%s') 
) (ess-funargs-command . .ess_funargs("%s") 
) (fill-nobreak-predicate quote ess-inside-string-p) (normal-auto-fill-function quote ess-do-auto-fill) (ess-execute-screen-options-command . options(width=%d, length=99999) 
)) 
(ess-mode-1.6): editing-alist=((paragraph-start concat \s-*$\| page-delimiter) (paragraph-separate concat \s-*$\| page-delimiter) (paragraph-ignore-fill-prefix . t) (require-final-newline . mode-require-final-newline) (indent-line-function quote ess-indent-line) (parse-sexp-ignore-comments . t) (ess-style . ess-default-style) (ess-mode-syntax-table . ess-r-syntax-table) (add-log-current-defun-header-regexp . ^\(.+\)\s-+<-[ 
]*function) (ess-font-lock-keywords quote ess-R-font-lock-keywords) (ess-font-lock-defaults ess--extract-default-fl-keywords ess-R-font-lock-keywords) (font-lock-defaults quote (ess-font-lock-defaults nil nil ((46 . w) (95 . w))))) 
(ess-setq-vars-LOCAL): language=S, dialect=R, buf=nil, comint..echoes=t, comint..sender=comint-simple-send 

Finished setting up ESS-mode. 
(n-i-m-l: 1)(ess-setq-vars-LOCAL): language=S, dialect=R, buf=nil, comint..echoes=t, comint..sender=comint-simple-send 
(ess-mode-1): ess-language=S, ess-dialect=R buf=Essai0.Rnw 
(ess-mode-1.5): alist=((inferior-ess-reload-function quote inferior-ess-reload:R) (ess-quit-function quote ess-quit:R) (ess-send-region-function quote ess-send-region:R) (ess-load-file-function quote ess-load-file:R) (ess-build-load-command-function quote ess-build-load-command:R) (ess-build-eval-command-function quote ess-build-eval-command:R) (ess-local-customize-alist quote ess-r-customize-alist) (ess-dialect . R) (ess-suffix . R) (ess-ac-sources . ess-r-ac-sources) (ess-company-backends . ess-r-company-backends) (ess-build-tags-command . ess-r-build-tags-command) (ess-traceback-command . ess-r-traceback-command) (ess-call-stack-command . ess-r-call-stack-command) (ess-mode-completion-syntax-table . ess-r-completion-syntax-table) (ess-build-eval-message-function function ess-r-build-eval-message) (ess-format-eval-command-function function ess-r-format-eval-command) (ess-format-load-command-function function ess-r-format-load-command) (ess-send-region-function function ess-r-send-region) (ess-load-file-function function ess-r-load-file) (ess-make-source-refd-command-function function ess-r-make-source-refd-command) (ess-format-eval-message-function function ess-r-format-eval-message) (ess-install-library-function function ess-r-install-library) (ess-eldoc-function function ess-r-eldoc-function) (ess-help-web-search-command function ess-r-sos) (ess-build-help-command-function function ess-r-build-help-command) (ess-dump-filename-template . ess-r-dump-filename-template) (ess-mode-editing-alist . ess-r-editing-alist) (ess-change-sp-regexp . ess-r-change-sp-regexp) (ess-help-sec-regex . ess-help-r-sec-regex) (ess-help-sec-keys-alist . ess-help-r-sec-keys-alist) (ess-loop-timeout . ess-r-loop-timeout) (ess-function-pattern . ess-r-function-pattern) (ess-object-name-db-file . ess-r-namedb.el) (ess-smart-operators . ess-r-smart-operators) (inferior-ess-program . inferior-ess-r-program-name) (inferior-ess-objects-command . inferior-ess-r-objects-command) (inferior-ess-font-lock-keywords quote inferior-ess-r-font-lock-keywords) (inferior-ess-search-list-command . search() 
) (inferior-ess-help-command . inferior-ess-r-help-command) (inferior-ess-help-filetype) (inferior-ess-exit-command . q()) (inferior-ess-exit-prompt . Save workspace image? [y/n/c]: ) (inferior-ess-start-file) (inferior-ess-start-args . ) (ess-error-regexp-alist . ess-r-error-regexp-alist) (ess-describe-object-at-point-commands quote ess-r-describe-object-at-point-commands) (ess-STERM . iESS) (ess-editor . ess-r-editor) (ess-pager . ess-r-pager) (ess-mode-syntax-table . ess-r-syntax-table) (font-lock-syntactic-face-function function ess-r-font-lock-syntactic-face-function) (prettify-symbols-alist quote ((<- . 8592) (<<- . 8606) (-> . 8594) (->> . 8608))) (ess-language . S) (inferior-ess-exit-command . q() 
) (inferior-ess-language-start eval inferior-S-language-start) (comint-use-prompt-regexp . t) (comint-process-echoes . t) (inferior-ess-primary-prompt . > ) (inferior-ess-secondary-prompt . + ) (comment-start . #) (ess-imenu-generic-expression . ess-imenu-S-generic-expression) (comment-add . 1) (comment-start-skip . #+ *) (comment-use-syntax . t) (comment-column . 40) (ess-no-skip-regexp concat ^ *@\| (default-value (quote ess-no-skip-regexp))) (inferior-ess-prompt . inferior-S-prompt) (ess-get-help-topics-function function ess-s-get-help-topics-function) (ess-getwd-command . getwd() 
) (ess-setwd-command . setwd('%s') 
) (ess-funargs-command . .ess_funargs("%s") 
) (fill-nobreak-predicate quote ess-inside-string-p) (normal-auto-fill-function quote ess-do-auto-fill) (ess-execute-screen-options-command . options(width=%d, length=99999) 
)) 
(ess-mode-1.6): editing-alist=((paragraph-start concat \s-*$\| page-delimiter) (paragraph-separate concat \s-*$\| page-delimiter) (paragraph-ignore-fill-prefix . t) (require-final-newline . mode-require-final-newline) (indent-line-function quote ess-indent-line) (parse-sexp-ignore-comments . t) (ess-style . ess-default-style) (ess-mode-syntax-table . ess-r-syntax-table) (add-log-current-defun-header-regexp . ^\(.+\)\s-+<-[ 
]*function) (ess-font-lock-keywords quote ess-R-font-lock-keywords) (ess-font-lock-defaults ess--extract-default-fl-keywords ess-R-font-lock-keywords) (font-lock-defaults quote (ess-font-lock-defaults nil nil ((46 . w) (95 . w))))) 
(ess-setq-vars-LOCAL): language=S, dialect=R, buf=nil, comint..echoes=t, comint..sender=comint-simple-send 

Finished setting up ESS-mode. 
(n-i-m-l: 1)(ess-setq-vars-LOCAL): language=S, dialect=R, buf=nil, comint..echoes=t, comint..sender=comint-simple-send 
(ess-mode-1): ess-language=S, ess-dialect=R buf=Essai0.Rnw 
(ess-mode-1.5): alist=((inferior-ess-reload-function quote inferior-ess-reload:R) (ess-quit-function quote ess-quit:R) (ess-send-region-function quote ess-send-region:R) (ess-load-file-function quote ess-load-file:R) (ess-build-load-command-function quote ess-build-load-command:R) (ess-build-eval-command-function quote ess-build-eval-command:R) (ess-local-customize-alist quote ess-r-customize-alist) (ess-dialect . R) (ess-suffix . R) (ess-ac-sources . ess-r-ac-sources) (ess-company-backends . ess-r-company-backends) (ess-build-tags-command . ess-r-build-tags-command) (ess-traceback-command . ess-r-traceback-command) (ess-call-stack-command . ess-r-call-stack-command) (ess-mode-completion-syntax-table . ess-r-completion-syntax-table) (ess-build-eval-message-function function ess-r-build-eval-message) (ess-format-eval-command-function function ess-r-format-eval-command) (ess-format-load-command-function function ess-r-format-load-command) (ess-send-region-function function ess-r-send-region) (ess-load-file-function function ess-r-load-file) (ess-make-source-refd-command-function function ess-r-make-source-refd-command) (ess-format-eval-message-function function ess-r-format-eval-message) (ess-install-library-function function ess-r-install-library) (ess-eldoc-function function ess-r-eldoc-function) (ess-help-web-search-command function ess-r-sos) (ess-build-help-command-function function ess-r-build-help-command) (ess-dump-filename-template . ess-r-dump-filename-template) (ess-mode-editing-alist . ess-r-editing-alist) (ess-change-sp-regexp . ess-r-change-sp-regexp) (ess-help-sec-regex . ess-help-r-sec-regex) (ess-help-sec-keys-alist . ess-help-r-sec-keys-alist) (ess-loop-timeout . ess-r-loop-timeout) (ess-function-pattern . ess-r-function-pattern) (ess-object-name-db-file . ess-r-namedb.el) (ess-smart-operators . ess-r-smart-operators) (inferior-ess-program . inferior-ess-r-program-name) (inferior-ess-objects-command . inferior-ess-r-objects-command) (inferior-ess-font-lock-keywords quote inferior-ess-r-font-lock-keywords) (inferior-ess-search-list-command . search() 
) (inferior-ess-help-command . inferior-ess-r-help-command) (inferior-ess-help-filetype) (inferior-ess-exit-command . q()) (inferior-ess-exit-prompt . Save workspace image? [y/n/c]: ) (inferior-ess-start-file) (inferior-ess-start-args . ) (ess-error-regexp-alist . ess-r-error-regexp-alist) (ess-describe-object-at-point-commands quote ess-r-describe-object-at-point-commands) (ess-STERM . iESS) (ess-editor . ess-r-editor) (ess-pager . ess-r-pager) (ess-mode-syntax-table . ess-r-syntax-table) (font-lock-syntactic-face-function function ess-r-font-lock-syntactic-face-function) (prettify-symbols-alist quote ((<- . 8592) (<<- . 8606) (-> . 8594) (->> . 8608))) (ess-language . S) (inferior-ess-exit-command . q() 
) (inferior-ess-language-start eval inferior-S-language-start) (comint-use-prompt-regexp . t) (comint-process-echoes . t) (inferior-ess-primary-prompt . > ) (inferior-ess-secondary-prompt . + ) (comment-start . #) (ess-imenu-generic-expression . ess-imenu-S-generic-expression) (comment-add . 1) (comment-start-skip . #+ *) (comment-use-syntax . t) (comment-column . 40) (ess-no-skip-regexp concat ^ *@\| (default-value (quote ess-no-skip-regexp))) (inferior-ess-prompt . inferior-S-prompt) (ess-get-help-topics-function function ess-s-get-help-topics-function) (ess-getwd-command . getwd() 
) (ess-setwd-command . setwd('%s') 
) (ess-funargs-command . .ess_funargs("%s") 
) (fill-nobreak-predicate quote ess-inside-string-p) (normal-auto-fill-function quote ess-do-auto-fill) (ess-execute-screen-options-command . options(width=%d, length=99999) 
)) 
(ess-mode-1.6): editing-alist=((paragraph-start concat \s-*$\| page-delimiter) (paragraph-separate concat \s-*$\| page-delimiter) (paragraph-ignore-fill-prefix . t) (require-final-newline . mode-require-final-newline) (indent-line-function quote ess-indent-line) (parse-sexp-ignore-comments . t) (ess-style . ess-default-style) (ess-mode-syntax-table . ess-r-syntax-table) (add-log-current-defun-header-regexp . ^\(.+\)\s-+<-[ 
]*function) (ess-font-lock-keywords quote ess-R-font-lock-keywords) (ess-font-lock-defaults ess--extract-default-fl-keywords ess-R-font-lock-keywords) (font-lock-defaults quote (ess-font-lock-defaults nil nil ((46 . w) (95 . w))))) 
(ess-setq-vars-LOCAL): language=S, dialect=R, buf=nil, comint..echoes=t, comint..sender=comint-simple-send 

Finished setting up ESS-mode. 
(n-i-m-l: 1)(ess-setq-vars-LOCAL): language=S, dialect=R, buf=nil, comint..echoes=t, comint..sender=comint-simple-send 
(ess-mode-1): ess-language=S, ess-dialect=R buf=Essai0.Rnw 
(ess-mode-1.5): alist=((inferior-ess-reload-function quote inferior-ess-reload:R) (ess-quit-function quote ess-quit:R) (ess-send-region-function quote ess-send-region:R) (ess-load-file-function quote ess-load-file:R) (ess-build-load-command-function quote ess-build-load-command:R) (ess-build-eval-com
```
Edited copy of the ESS bug report ends :

**Comment by vspinu** [comment]
This is an issue with local variables set within the buffer. They are not "lost", they are not taken effect I guess.

**Comment by EmmanuelCharpentier** [comment]
I'm afraid it may be a bit more complicated that that : what I mean is : 
* Starting afresh, and evaluating (via `M-:`) the form `(buffer-local-value 'TeX-master (current-buffer))` yelds `"Essai0"` in tjhe `*Messages*` buffer ;
* moving inside the `Firstrchunk` chunk and re-evaluating yelds `t`in the `*Messages*` buffer ;
* moving _outside_ the `Firstrchunk` chunk and re-re-evaluating still yelds `t` ;
* ressetting AUCTeX (vla `C-u C-c C-n`) without moving the cursor and re-re-re-evaluatng the same form yelds `"Essai0"` again.

Curiously, `(assoc 'file-local-variables-alist (buffer-local-variables (current-buffer)))` always yelds `(file-local-variables-alist (TeX-master . "Essai0") (TeX-engine . default) (mode . poly-noweb+R-mode))`, whether you are afresh, in the R chunck or gone out of it.

HTH,

**Comment by vspinu** [comment]
> what I mean is :

Oh. I see. This is by design (or rather by how polymode is implemented - through indirect buffers). If you want some variables to be moved between buffers (chunks) you need to add them to `pm-move-vars-from-base` or `pm-move-vars-from-old-buffer`. In your case it's the former variable.

**Comment by vspinu** [comment]
> moving outside the Firstrchunk 

Do you mean that after returning to AucTeX chunk you see `t`? That's cannot be, or it's a bug indeed.

**Comment by vspinu** [comment]
I cannot reproduce this BTW. In AuctTeX it's always Essai0, in all other chunks it's `nil`. 

> M-n r still correctly knits Essai0.Rnw to Essai0.tex

There is no `M-n r` in polymode, only `M-n w` (weave) and `M-n e` (export). Looks like you are still using ess-noweb mode and not polymode.

> C-c C-c tries to LaTeX Essai0.Rnw, which fails on line 3, 

This is expected, auctex doesn't know about Rnw files. This is why we need `M-n e`, but I think it won't pick TeX-master I am afraid. A tighter integration with AucTeX would be nice; one just needs to implement an [auctex exporter](https://github.com/vspinu/polymode/blob/next/modes/poly-noweb.el#L75-L121) which would redirect compilation to AucTeX.

**Comment by EmmanuelCharpentier** [comment]
> > moving outside the Firstrchunk

> Do you mean that after returning to AucTeX chunk you see t?

Yes.

> That's cannot be,

It is. Try it for yourself.

> or it's a bug indeed.

Indeed it is... Hence my report on ESS-_bugs_ (I have exacty the same problem with `Rnw-mode`)...

**Comment by EmmanuelCharpentier** [comment]
> There is no M-n r in polymode, only M-n w (weave) and M-n e (export). Looks like you are still using ess-noweb mode and not polymode.

Ah. I _thought_ that this was what `poly-noweb+R` was supposed to do (i. e. using ESS's `noweb` mode if available).

OK. I may have a better chance going back to ESS's `Rnw-mode`... which has _exactly_ the same problem.

What I want to accomplish is

1. Use ESS's `Rnw-mode`, which does what I want (modulo the loss of `TeX-master` and `TeX-engine` after mode switches), i. e. use of ESS's nowsb-mode, with all its perks, for R code and use AUCTeX (with all its perks) for LaTeX, withou having t constantly reset AUCTeX. This is my current issue.

This accomplished, I wish for : 

2. a polymode using `Rnw-mode` (or `polyè-noweb+R`) for LaTeX and R code and [`sage-shell:sage-mode`](https://github.com/sagemath/sage-shell-mode) for [Sage](www.sagemath.org) code.

A further enhancement/extension of this might be : 

3. A polymode using AUCTeX's `latex-mode` as its base, some `noweb` mode (possibly ESS's) for R code and a `Python` mode for various variations over Python and usable by [Pythontex](https://github.com/gpoore/pythontex). _That_ could include Sage, since Sage is esentially a (slightly) modified Python 2.

(Note : I tried to implement 2) by writing a polymode using the same ingredients as `poly-noweb+R` and adding a Sage inner mode, but this one stops on error when switching back to LaTeX. I also tried a polymode with `Rnw-mode` as hostmode and a Sage inner mode : same result. But I did not yet debug them, since I stumbled on the present bug (existing in both `Rnw-mode` and `poly-nowsb+R`), and this is _not_ my subject now).

**Comment by vspinu** [comment]
> which has exactly the same problem.

Polymode doesn't have the problem what you described. It's not possible by design. Modes are not reset when you move between chunks, as it is the case with other multi-modes (e.g. ess-noweb). 

Make sure you are indeed in polymode (PM should appear in the modeline and `pm/polymode` should be defined).

>  I wish for :

I don't see why python wouldn't work if you do just what `poly-noweb-R` does. Python works in md files and should work in `.pynw` files if you did the right thing.

In long run, noweb should accept mode name and behave like markdown (i.e. identify modes on the fly). Unfortunately I don't have time at the moment to improve or even maintain polymode, so this has to wait.

**Comment by EmmanuelCharpentier** [comment]
> > which has exactly the same problem.

> Polymode doesn't have the problem what you described. It's not possible by design. Modes are not reset when you move between chunks, as it is the case with other multi-modes (e.g. ess-noweb).

If you can find d the time, please have a look at my original report on `ESS-bugs`. I described what I saw in a "minimal" environment.

> In long run, noweb should accept mode name and behave like markdown (i.e. identify modes on the fly).

That would be indeed very handy.

> Unfortunately I don't have time at the moment to improve or even maintain polymode, so this has to wait.

I can understand that ;-).

I'll try to debug `Rnw-mode` and understand what happens in this case. Is there a place wher I can keep you posted on my findings ? Maybe file a new issue in the Github page for ESS ?

**Comment by vspinu** [comment]
> s there a place wher I can keep you posted on my findings ? 

ESS github bug tracker, but ess-noweb is half deprecated. So, it's unlikely that anyone would ever pick it up or fix the issue. Polymode was intended as a replacement, but well ... things are how they are.

**Comment by vspinu** [comment]
I have re-read the issue again and it's almost surely concerning ess-noweb. So there is nothing I can do in here. I am working on an improved version of polymode which hopefully will be available within a week or two on MELPA. Once there, consider switching to polymode and report new issues here.

**Comment by EmmanuelCharpentier** [comment]
Thank you for letting me know. I regularly update my `emacs` packages, so I should see a newer version of `polymode` land down (I' currently at `20170307.1122`), and I'll be happy to test it. If you think of useful tests I could do, pleas ask !

Again, thank you for `polymode` : I' currently working on a paper with a co-author who insists on .Rmd, and `emacs` + `polymode` is a lifesaver...

**Comment by vspinu** [comment]
Not in MELPA yet. Will likely take another week or two. I am in the process of refactoring the package at the moment.
