### ISSUE TITLE
common lisp/slime support?

### ISSUE THREAD

**Issue by slyrus** [vspinu/polymode#154]
R/ESS support is great, thanks! Any chance of supporting chunks of common lisp code (preferably via slime/SWANK)?

**Comment by vspinu** [comment]
Not as part of the package. Users should create their own extension.

**Comment by slyrus** [comment]
Can you point me to a good example of an extension? thanks!

**Comment by vspinu** [comment]
[poly-R](https://github.com/vspinu/polymode/blob/master/modes/poly-R.el) is probably what you need, but you need just a fraction of that. For having common lisp chunks, a regexp for header and tail is enough. Things like weavers and exporters are a bit more complicated.

**Comment by slyrus** [comment]
Ok, thanks. It doesn't like there's an emacs lisp polymode either. Am I missing something?

**Comment by vspinu** [comment]
There is no such thing as "lisp" or "R" polimode. It's always a combination of host mode with child mode(s). (e)Lisp works in markdown (as any other mode defined). 

Do you have a use case in mind? What is your host-mode?

**Comment by vspinu** [comment]
In markdown any mode should work (but there are issues with recent markdown which I still have to sort out). 

If it doesn't work it's because markdown abreviation doesn't match the emacs mode. See `polymode-mode-name-override-alist`.

**Comment by asciian** [comment]
@slyrus Hi, I have made it a years ago and named papyrus which works well with polymode.Please check it. 

https://github.com/asciian/papyrus
