### ISSUE TITLE
[next] Emacs hangs when killing/pasting in larger documents

### ISSUE THREAD

**Issue by theGreatWhiteShark** [vspinu/polymode#159]
When in branch **next** fontification and everything else works flawlessly. 

But when killing/pasting paragraphs in large documents (1177 lines/67KB) Emacs freezes and still occupies 100% of one core (Acer Aspire S3) after 3.5 minutes. Also the interaction "feels" more slow in larger documents.

For smaller ones everything is fine.

I haven't checked yet which hook is causing the problem. I'll try to do so before the weekend.

**Comment by vspinu** [comment]
Which mode is this? I do see the sllugishness in large documents and I already removed one source of it, but will have to investigate and optimize more. 

I don't see the killing/yanking problem though. Does it occur in kill or on yank? Would it be possible for you to privately share the document where kill/yank problem occurs?

**Comment by vspinu** [comment]
Actually I don't see the sluggishness on the comparable document size. I had tracing on when I checked last time. Would you mind profiling and sending the output here. 

```
M-x profiler-start RET RET
## do some editing which feels sluggish
M-x profiler-report
M-x profiler-stop
## go to the profiler window and expand all entries with `C-u TAB`
```

**Comment by vspinu** [comment]
Also please make sure you are using the latest [next] branch and have no traces of older polymode (MELPA or not).

**Comment by vspinu** [comment]
Forgot to say, [next] works reliably in emacs 25+ only.

**Comment by theGreatWhiteShark** [comment]
I'm in `poly-markdown+r-mode` within
```
(emacs-version)
```
> "GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.11)
 of 2018-05-25"

Latest branch and no traces of older versions.

I was able to pin it down to the insertion of a new `{#sec:test}` tag behind a heading (in the latter part of the document). The killing and yanking described earlier did include at least one of those tags. Unfortunately I can not profile this step since Emacs won't respond anymore afterwards. I'll try to reproduce the "slowdown" and profile it soon.

**Comment by vspinu** [comment]
No matter what I do with `{#sec:test}` it does not create any problems. I am pretty sure such severe infloop could be caused only by the re-display. The only way to stop the lock is to kill the top buffer or switch away from it. For me `C-g C-g C-g ... M-8` would usually work where `M-8` is bound to `bury-buffer`. 

> I'll try to reproduce the "slowdown" and profile it soon.

Thanks. 

One way to get more info on what's happening is to `M-x pm-debug-toggle-verbose`.

**Comment by vspinu** [comment]
No, it's not worth your time at this moment. I am pushing major changes every day. 

Some error messages might still be coming occasionally due to a bug in markdown proper but general experience at this moment should be more than satisfactory.

**Comment by theGreatWhiteShark** [comment]
Okay. Thanks a lot!
