### ISSUE TITLE
Polymode with color themes

### ISSUE THREAD

**Issue by seandavi** [vspinu/polymode#18]
I have adopted polymode as my standard ESS/R editing mode--works great so far.  Recently, I tried using some of the color themes that ship with Emacs 24 and noticed that none of them work out-of-the-box with polymode/r-markdown because the code sections show up as highlighted, making text nearly unreadable.  Any suggestions on how to alter behavior so that the color themes work better?  I can (and have) set the color themes myself, but wondered about making things more compatible with the standard themes.  

I realize this is probably not a polymode problem, but thought I would ask experienced users what they are doing.

**Comment by vspinu** [comment]
The background of chunks is correct in new files even after a theme is loaded. I think that's good enough. I don't see any hooks in `load-theme`, so adapting the background of chunks on the fly would need to be hacky. Given that this is such a small inconvenience I am not improving on this one further for now.
