### ISSUE TITLE
Wrong number of arguments?

### ISSUE THREAD

**Issue by mittenchops** [vspinu/polymode#25]
I may be using this completely incorrectly, but I tried exporting my Rmd to LaTeX:

```
Title
====================================

Here's some test!

\```{r md-cars-scatter, message=FALSE, fig.width=7, fig.height=5}
library(ggplot2)
qplot(hp, mpg, data=mtcars)+geom_smooth() 
\```
```

Then ```M-n e``` as I understood this to be sort of the evaluate keystroke.  

Got an error in my buffer that I had the wrong number of arguments...

![wrongnumberofarguments](https://cloud.githubusercontent.com/assets/1584795/3027662/0446acdc-e025-11e3-9484-a25ab2f74ea4.png)

I'm using the polymode from the MELPA repositories.

**Comment by vspinu** [comment]
The weaving/exporting got rewritten. This issue should be gone.
