### ISSUE TITLE
Add weaver for new rmarkdown

### ISSUE THREAD

**Issue by memeplex** [vspinu/polymode#30]
The knit->rmarkdown pipeline has changed recently, as rmarkdown is now a frontend intended to call knit and pandoc behind the scenes. So rmarkdown is not strictly weaving but going all the way through html. Anyway I feel it's more appropriate to provide this "weaver" at the polymode level than at the markdown-mode level. What do you think?

**Comment by dojeda** [comment]
Excellent snippet @malcook !
For me, however, the output is display both in the *Shell Command Output* buffer and the *Messages* buffer, which is quite annoying.
I resolved this by putting a & at the end of the shell command, which executes the rendering asynchronously and only outputs to the *Async Shell Command* buffer

**Comment by r2evans** [comment]
Another technique I switched to is using `smart-compile` to automatically default to the correct Rscript call (instead of the default `make -k`), and just use `compile` to render the document. It does color-ify the output meaningfully, though admittedly it doesn't know enough about the output to be able to jump to the source document line for an error.

**Comment by biocyberman** [comment]
@malcook Could you change the function so that it works for files open through ssh connection with Tramp? I tried to render a file like that and the fuction does not understand the ssh protocol and the colons `:`

**Comment by malcook** [comment]
@biocyberman - I think would be satisfied if the snippet ran `Rscript ...` not on localhost but rather on the host associated with tramp session through which you are editing the file.  Does that make sense?  Would that suit your purpose?

**Comment by biocyberman** [comment]
@malcook With only a typo with three additional ))), the functions now works like a charm over tramp :+1:

**Comment by malcook** [comment]
Glad it helped.  

About those trailing parens, I think I lost them to an emacs core dump while coding for my master thesis over 30 years ago - glad to have 'em back - thanks for the alert!

**Comment by kwstat** [comment]
My approach.  Renders Rmd to html and opens in browser.  Derived from: delhey.info/inc/ess-rmarkdown.pdf

```
(define-key polymode-mode-map (kbd "M-n r") 'ess-render-rmarkdown)

(defun ess-render-rmarkdown ()
  "Compile R markdown (.Rmd). Should work for any output type."
  (interactive)
  ;; Check if attached R-session
  (condition-case nil
      (ess-get-process)
    (error
     (ess-switch-process)))
  (let* ((rmd-buf (current-buffer)))
    (save-excursion
      (let* ((sprocess (ess-get-process ess-current-process-name))
             (sbuffer (process-buffer sprocess))
             (buf-coding (symbol-name buffer-file-coding-system))
             (buffer-file-name-html (concat (file-name-sans-extension buffer-file-name) ".html"))
             (R-cmd
              (format "library(rmarkdown); rmarkdown::render(\"%s\"); browseURL(\"%s\")"
                      buffer-file-name buffer-file-name-html)))
        (message "Running rmarkdown on %s" buffer-file-name)
        (ess-execute R-cmd 'buffer nil nil)
        (switch-to-buffer rmd-buf)
        (ess-show-buffer (buffer-name sbuffer) nil)))))
```

**Comment by malcook** [comment]
@kwstat  - big difference with your approach is that it (re)-uses current R process which may have some state (i.e. variables set) which would not be present when starting a new R process, such as my approach.  "You get what you asked for"

**Comment by vspinu** [comment]
This part has been finally done. There is now two fully featured exporters (`M-n e`)  one for ESS and one for Rscript standalone. Thanks for your patience.
