### ISSUE TITLE
Polymode on a text file with Python chunks crashes Emacs

### ISSUE THREAD

**Issue by smaret** [vspinu/polymode#36]
I'm trying to define a polymode to edit a text file with some Python chunks. When I edit the text file with this mode, Emacs crashes. 

Here are the steps to reproduce the problem:

1. Open ```test-mode.el``` file from this [gist](https://gist.github.com/smaret/062a882305b5b95f5309) and run ```M-x eval-buffer```
2. Open the ```test.txt``` file (also in the gist) and run ```M-x poly-test-mode```
3. Go to the 3rd line (just after the ```begin ``` block and type ```Ctrl-k``` to delete a line. Move around with the arrow keys. Emacs crashes.

I use Emacs 24.3 from MacPorts (```emacs-app@24.3``` port) on MacOS 10.9.4, and ```polymode 20140614.1301``` from MELPA.

**Comment by smaret** [comment]
I can't reproduce this bug with Emacs 24.5 and `polymode 20150729.734` from MELPA. I suppose it has been fixed somehow.

**Comment by vspinu** [comment]
Yes. It was fixed mostly on emacs side.
