### ISSUE TITLE
Hanging when editing in cloud

### ISSUE THREAD

**Issue by naruchan** [vspinu/polymode#39]
I'm using polymode with Emacs 24.3.1. When editing R markdown files locally on my computer, everything works smoothly. However, if I try to edit them on a remote server (I'm in a work environment where code doesn't normally sit on our local machines), Emacs slows to an unusable crawl with polymode enabled. 

There error messages that spam the buffer seems to point to jit-lock-function (where somefile is a filepath on the server):

Error during redisplay: (jit-lock-function 1074) signaled (error "IO error reading /somefile: Is a directory")

What is it trying to read that it can't find? Is there a workaround? Let me know if there's more info I can provide. Thanks!

-Sharon

**Comment by vspinu** [comment]
I am closing this as non polymode issue. It has been fixed long time ago on ESS side and some more optimization and re-factoring is happening for the new release of eSS.
