### ISSUE TITLE
Polymode with evil-mode conflict

### ISSUE THREAD

**Issue by vsbuffalo** [vspinu/polymode#41]
It looks like polymode is conflicting somehow with navigation in evil-mode. For example, if I create a simple `test.Rmd` file, with the following it it:

    ```{r}

    ```

and go to the bottom of the buffer (add in some extra newlines), and then navigate upwards with `k` in evil-mode, the following happens:

    `k``{r}

    k```

There's also something funky going on with typing:

    ```{r

where entering the final `}` moves the cursor (?).

**Comment by vsbuffalo** [comment]
I just want to update this — there is also a *very* bad bug whereby evil-mode with undo-tree will absolutely lead to a destruction of your undo history when used with poly-mode. Undo will quickly insert gibberish in buffers in polymode and the lack of a working undo only makes this work. Beware!

**Comment by lionel-** [comment]
I also had this problem but didn't know it was caused by undo-tree. I lost data a few times. Thanks for the information!

**Comment by vsbuffalo** [comment]
Is there any update on this?

**Comment by vspinu** [comment]
Not really. Sorry. There are too many non-trivial issues to deal with and I haven't had time to get into it as yet. But I will surely do, sooner or later.

**Comment by holtzermann17** [comment]
Although it's for a different package, it looks like this is the idea: https://github.com/tarao/multi-mode-util/blob/master/multi-mode%2Bevil.el

**Comment by lionel-** [comment]
it would be very nice for someone to write such a package, tough I don't have time to write one in the foreseeable future.

This package could also provide the following text objects for chunks:
```lisp
  (defun polymode-mark-inner-chunk ()
    (let ((span (pm/get-innermost-span)))
      (set-mark (1+ (nth 1 span)))
      (goto-char (1- (nth 2 span)))))

  (defun polymode-mark-chunk ()
    (let ((span (pm/get-innermost-span)))
      (goto-char (nth 1 span))
      (set-mark (line-beginning-position))
      (goto-char (nth 2 span))
      (goto-char (line-end-position))))

  (evil-define-text-object evil-a-polymode-chunk (count &optional beg end type)
    "Select a polymode chunk."
    :type line
    (polymode-mark-chunk))

  (evil-define-text-object evil-inner-polymode-chunk (count &optional beg end type)
    "Select inner polymode chunk."
    :type line
    (polymode-mark-inner-chunk))
```

**Comment by vspinu** [comment]
I have finally added integration for evil mode. Sorry for taking so long. 

My understanding of modal editing hardly goes beyond `hjkl` but it seems to work as expected. I would very much like to hear form an evil user that it actually works.

Inspired by the [multi-mode-evil.el](https://github.com/tarao/multi-mode-util/blob/master/multi-mode%2Bevil.el) I have introduced a custom variable:

```
(defcustom polymode-evil-states '(normal insert emacs)
  "States of evil-mode to be preserved when switching indirect buffers."
  :type '(symbol)
  :group 'polymode-compat)
```

Is this really needed? Don't you want to preserve all the states when moving between spans and chunks?

**Comment by holtzermann17** [comment]
On Sun, Feb 28, 2016 at 1:39 AM, Vitalie Spinu <notifications@github.com>
wrote:

> Don't you want to preserve all the states when moving between spans and
> chunks?
>

That policy makes sense to me.

(I'll try to test the changed mode soon.)

**Comment by vspinu** [comment]
Ok. So I am keeping same state regardless of the state. We can change that anytime. Just let me know if you have any problems.

**Comment by roryk** [comment]
@vspinu, this is AWESOME.

**Comment by philipphoman** [comment]
Same here, using evil-mode. Undo history corrupted.

**Comment by vspinu** [comment]
Undo movement between indirect buffers is handled by emacs internals. If undo is corrupted that could mean something is not quite right other there. IN any case I would apreciate a reproducible example here. Would you mind opening a new issue for this?

**Comment by jody-frankowski** [comment]
This should be a reproducible example: https://github.com/polymode/polymode/issues/214
