### ISSUE TITLE
Invalid function: eieio--object-name

### ISSUE THREAD

**Issue by senor-hadoop** [vspinu/polymode#46]
Does anyone know of a reason why a fresh checkout of polymode would give me the error in the subject line when trying to export? I'm wondering if it might be because of pandoc, but I also get it with M-n w after setting my weaver to knitR-ESS.

At the end of the day I'm trying to use Rmarkdown with ESS and knitr.

Has anyone got this combination working?

Cheers,
    - Steve

**Comment by sbacelar** [comment]
Same problem. Version 24.4 on MacOS 10.10.2

**Comment by vspinu** [comment]
This one seems to be fixed. I cannot reproduce it with Emacs 24.4.1 nor even 23.1 which is the earliest I am supporting at the moment. Feel free to re-open if you think it's still not fixed.
