### ISSUE TITLE
polymode font-lock error

### ISSUE THREAD

**Issue by nrnrnr** [vspinu/polymode#51]
I'm getting this error from polymode:

````
polymode font-lock error: Lisp nesting exceeds `max-lisp-eval-depth' (beg: 1 end: 126)
polymode font-lock error: Lisp nesting exceeds `max-lisp-eval-depth' (beg: 126 end: 633)
polymode font-lock error: Lisp nesting exceeds `max-lisp-eval-depth' (beg: 633 end: 1159
````

In conjunction with this error, the LaTeX is not getting highlighted.

Unfortunately I cannot attach the file; it contains private information.  I tried expurgating the private information, but I am unable to duplicate the error with the expurgated file.

I installed polymode from MELPA and I appear to have version `20141204.2346`.  I'm running emacs 24.3.1.

**Comment by vspinu** [comment]
Related to #51 and #53
