### ISSUE TITLE
Emacs crash with polymode and lua-mode

### ISSUE THREAD

**Issue by AndreasMatthias** [vspinu/polymode#52]
I experience crashes of emacs related to polymode and lua-mode, mostly when hitting delete-key (delete-forward-char). Here is a description of how to replicate this crash:

1. `emacs --no-splash --no-site-file --no-init-file -l foo.el`
2.  hit delete-key twice

I'm running Emacs 24.3.1. Testing the same with Emacs 25.0.50.2 I experience the same crash, but now the crash is not restricted to the delete-key but happens with other keys as well, e.g. hitting `a' twice.

With Emacs 25.0.50.2 I get theses failed assertions:

1. Pressing delete-key twice:
  `xdisp.c:18439: Emacs fatal error: assertion failed: MATRIX_ROW_DISPLAYS_TEXT_P (last_row)`

2. Pressing \`a'-key twice:
  `xdisp.c:17524: Emacs fatal error: assertion failed: row->enabled_p`

* File: foo.el
```lisp
(add-to-list 'load-path "~/.emacs.d/elpa/polymode-20141204.2346/")
(add-to-list 'load-path "~/.emacs.d/elpa/lua-mode-20141025.1746/")
(require 'lua-mode)
(require 'poly-noweb)

(defcustom pm-poly/noweb+foobar
  (pm-polymode-multi "noweb"
                     :hostmode 'pm-host/latex
                     :innermodes '(pm-inner/noweb+lua)
                     :exporters '(pm-exporter/latexmk pm-exporter/pdflatex)
                     :map '(("<" . poly-noweb-electric-<))
                     )
  "Noweb typical configuration"
  :group 'polymodes
  :type 'object)

(defcustom pm-inner/noweb+lua
  (pm-hbtchunkmode "noweb+lua"
                   :mode 'lua-mode
                   :head-reg  "<<\\(.*\\)>>="
                   :tail-reg    "\\(@ +%def .*\\)$\\|\\(@[ \n]\\)")
  "Noweb innermode for Lua"
  :group 'innermodes
  :type 'object)

(define-polymode poly-noweb+foobar-mode pm-poly/noweb+foobar
  :lighter "PM-Lua")


(find-file "foo.nw")
(poly-noweb+foobar-mode)
(next-line)
(next-line)
(next-line)
(next-line)
```

* File: foo.nw
```
@
<<test>>=
function foobar ()
   if true then
 
      foo()
   end
end
@
```

Andreas

**Comment by AndreasMatthias** [comment]
Should I report this bug to the Emacs bug list?

I know there are controversial discussions about indirect buffers and I don't want to in flame this discussion. But then a crash of Emacs is never acceptable and should be reported.

The failed assertions (mentions in my first post) are on the C side in redisplay(), a very low level function. I'm not sure if isolating the elisp code that triggers these assertions is of much use for debugging such low level C functions.

**Comment by vspinu** [comment]
You are absolutely right, such crashes are not permissible. You can surely report it if you want. 

In early 2014 fontlock in indirect buffers was disabled which completely ruined polymode. So I fixed it in a hurry by activating it back:) It's quite likely this issue is related to that workaround.

**Comment by AndreasMatthias** [comment]
Done. See Emacs bug report [#19511](http://debbugs.gnu.org/cgi/bugreport.cgi?bug=19511).

**Comment by vspinu** [comment]
Hi Andreas, 

Thank you very much for that bug report. I am removing the offending `bury-buffer` for time being. 

Your lua-mode code could be simplified into:

```
(require 'poly-noweb)

(defcustom pm-poly/noweb+lua
  (clone pm-poly/noweb
         :innermode 'pm-inner/noweb+lua)
  "Noweb for lua configuration"
  :group 'polymodes
  :type 'object)

(defcustom pm-inner/noweb+lua
  (clone pm-inner/noweb
         :mode 'lua-mode)
  "Noweb for lua"
  :group 'innermodes
  :type 'object)

(define-polymode poly-noweb+lua-mode pm-poly/noweb+lua
  :lighter "PM-Lua")
```

Do you object if I add it this to polymode modes and your test file as well?

**Comment by AndreasMatthias** [comment]
Hi Vitalie,

Vitalie Spinu wrote:

> Thank you very much for that bug report. I am removing the offending bury-buffer for time
> being.

Just tried your last commit. Looks good.

After fixing emacs I experienced a noticeable performance loss. But with
your latest commit it feels like this loss vanished. Great.

> Your lua-mode code could be simplified into:
>
> (require 'poly-noweb)
>
> (defcustom pm-poly/noweb+lua
>   (clone pm-poly/noweb
>          :innermode 'pm-inner/noweb+lua)
>   "Noweb for lua configuration"
>   :group 'polymodes
>   :type 'object)
>
> (defcustom pm-inner/noweb+lua
>   (clone pm-inner/noweb
>          :mode 'lua-mode)
>   "Noweb for lua"
>   :group 'innermodes
>   :type 'object)
>
> (define-polymode poly-noweb+lua-mode pm-poly/noweb+lua
>   :lighter "PM-Lua")

I see. 

But: I'm using several inner modes. (Which was working fine with my approach
of just copying the stuff.) How do I get several inner modes with
cloning? I tried the following, which didn't work.

(defcustom pm-poly/noweb+lua
  (clone pm-poly/noweb
         :innermodes '(pm-inner/noweb+lua
                       pm-inner/noweb+MetaPost)
         )
  "Noweb for lua configuration"
  :group 'polymodes
  :type 'object)


> Do you object if I add it this to polymode modes and your test file as well?

No objections.

Ciao
Andreas

**Comment by vspinu** [comment]
> But: I'm using several inner modes. (Which was working fine with my approach of just copying the stuff.) How do I get several inner modes with cloning? I tried the following, which didn't work. 

Ah sorry. Sure. I have missed that you have used `pm-polymode-multi`. In the example you have only one inner mode (lua). I guess your real life example is more involved. How do you differentiate between difernt mode chunks?

**Comment by AndreasMatthias** [comment]
Vitalie Spinu wrote:

> Ah sorry. Sure. I have missed that you have used pm-polymode-multi. In the example you
> have only one inner mode (lua). I guess your real life example is more involved. How do
> you differentiate between difernt mode chunks?

I use  ":head-reg". Most chunks are lua code therefore they get the
universal

    :head-reg  "<<\\(.*\\)>>="

other chunks get specialized tag names:

    :head-reg "<<MetaPost.*>>="
    :head-reg "<<LaTeX .*>>="

Yes, I'm having inner LaTeX modes as well.


Andreas

**Comment by AndreasMatthias** [comment]
I'm afraid I didn't get Norman's view on special chunk names.

I am having only a few non-Lua chunks, and giving these chunks a special chunk name is no issue for me. Maybe things would be different if I had more non-Lua chunks. I'm not sure. This is the first time I'm working with chunks of several different programming languages.

> I personally don't have any preferences on how to detect the mode of a chunk, except that it should be somewhat standardized with other tools if there are any.

I don't think there is any "standard". But I'm sure Norman can tell us more.

I was working with mumamo.el before but wasn't very happy with it.
Polymode is the best I've seen so far.

**Comment by nrnrnr** [comment]
> > I use ":head-reg". Most chunks are lua code therefore they get the
 > > universal :head-reg "<<\\(.*\\)>>=" other chunks get specialized tag
 > > names: :head-reg "<<MetaPost.*>>=" :head-reg "<<LaTeX .*>>=" Yes, I'm
 > > having inner LaTeX modes as well...
 > 
 > Ok That's interesting. I think a new  `poly-noweb-auto-mode`  is needed...
 > 
 > I personally don't have any preferences on how to detect the mode of a
 > chunk, except that it should be somewhat standardized with other tools if
 > there are any.

There is a standard established maybe 15 years ago, I think by Lee
Wittenberg:

  - Root chunks are classified by means not specified, but typically a
    glob pattern matching the name.  For example, the glob patterns
    *.h and *.c would classify to C code.

    I personally am a big fan of glob patterns, but for consistency
    with other emacs tools, regexps are probably to be preferred.

  - The mode of a non-root chunk is propagated from its ancestor root
    chunk by following def-use chains.

Open questions:

  - Can the classifying regexps/patterns be buffer-local, or must they
    be attached to a particular mode?  I see advantages to both
    schemes.

  - What happens to a root chunk that is not classified by any
    pattern?  Probably fundemental-mode is a good decision here.
    But a default mode for unclassified could also be stored in a
    buffer-local variable.  This possibility would have advantages of
    near-compatibility with prior implementations of noweb-mode,
    easing migration.


Norman
