### ISSUE TITLE
font-lock error "Args out of range"

### ISSUE THREAD

**Issue by nrnrnr** [vspinu/polymode#54]
I continue to have difficulty with polymode's noweb support.  At startup, I am getting a bunch of font-lock errors:

````
polymode font-lock error: Args out of range: 1, 655 (beg: 519 end: 1081)
polymode font-lock error: Args out of range: 1, 747 (beg: 519 end: 1081)
polymode font-lock error: Args out of range: 1, 787 (beg: 519 end: 1081)
polymode font-lock error: Args out of range: 1, 816 (beg: 519 end: 1081)
polymode font-lock error: Args out of range: 1, 899 (beg: 519 end: 1081)
polymode font-lock error: Args out of range: 1, 1360 (beg: 1081 end: 1622)
polymode font-lock error: Args out of range: 1, 1679 (beg: 1622 end: 2124)
polymode font-lock error: Args out of range: 1, 1746 (beg: 1622 end: 2124)
polymode font-lock error: Args out of range: 1, 1847 (beg: 1622 end: 2124)
polymode font-lock error: Args out of range: 1, 2049 (beg: 1622 end: 2124)
````

The file in question is a part of an unpublished book, which I cannot make public. But 
I have created private repository https://github.com/nrnrnr/polymode-error and have given you access.
This should enable you to reproduce the error.

**Comment by nrnrnr** [comment]
This bug is a showstopper.  I have some time to help, if you have time to track it down.

**Comment by billdenney** [comment]
I'm experiencing a similar issue.  The file that I'm working with is attached.

The most recent of the many similar errors is:
    polymode font-lock error: Args out of range: 1025, 1026 (beg: 1226 end: 1745)

[Introduction-and-Usage.txt](https://github.com/vspinu/polymode/files/102425/Introduction-and-Usage.txt)

**Comment by roryk** [comment]
I see these errors still:


```
(poly-lock-fontify-region 2101 4096) -> (font-lock-default-fontify-region 3092 3094 nil): Args out of range: 3076, 3079 
(poly-lock-fontify-region 2101 4096) -> (font-lock-default-fontify-region 3364 3366 nil): Args out of range: 3348, 3351 
(poly-lock-fontify-region 2101 4097) -> (font-lock-default-fontify-region 3093 3095 nil): Args out of range: 3076, 3079 
(poly-lock-fontify-region 2101 4097) -> (font-lock-default-fontify-region 3365 3367 nil): Args out of range: 3348, 3351 
(poly-lock-fontify-region 2101 4098) -> (font-lock-default-fontify-region 3094 3096 nil): Args out of range: 3076, 3079 
(poly-lock-fontify-region 2101 4098) -> (font-lock-default-fontify-region 3366 3368 nil): Args out of range: 3348, 3351 
(poly-lock-fontify-region 2101 4097) -> (font-lock-default-fontify-region 3093 3095 nil): Args out of range: 3076, 3079 
(poly-lock-fontify-region 2101 4097) -> (font-lock-default-fontify-region 3365 3367 nil): Args out of range: 3348, 3351 
(poly-lock-fontify-region 2373 4099) -> (font-lock-default-fontify-region 3095 3097 nil): Args out of range: 3076, 3079 
(poly-lock-fontify-region 2373 4099) -> (font-lock-default-fontify-region 3367 3369 nil): Args out of range: 3348, 3351 
(poly-lock-fontify-region 2101 4097) -> (font-lock-default-fontify-region 3093 3095 nil): Args out of range: 3076, 3079 
(poly-lock-fontify-region 2101 4097) -> (font-lock-default-fontify-region 3365 3367 nil): Args out of range: 3348, 3351 
Buffer is read-only: #<buffer *Compile-Log*>
(poly-lock-fontify-region 2101 4097) -> (font-lock-default-fontify-region 3093 3095 nil): Args out of range: 3076, 3079 
(poly-lock-fontify-region 2101 4097) -> (font-lock-default-fontify-region 3365 3367 nil): Args out of range: 3348, 3351 
(poly-lock-fontify-region 2101 4097) -> (font-lock-default-fontify-region 3093 3095 nil): Args out of range: 3076, 3079 
(poly-lock-fontify-region 2101 4097) -> (font-lock-default-fontify-region 3365 3367 nil): Args out of range: 3348, 3351 
```

The file I'm working with is here: https://raw.githubusercontent.com/hbc/scadden-crispri/b6ce7b5ae0f0815e7875673439fc34e6ce241a57/analysis/analysis-from-counts.Rmd

I can reproduce the error if I go into the cleanup-count-files block and start editing. Emacs used to hard-lock on this as of a couple days ago but updating from MELPA seems to have fixed that.

**Comment by roryk** [comment]
Spoke too soon. It hard locks after editing for a while, with similar errors. I'm not too sure how to debug what it is doing when it is spinning the CPU though.

**Comment by vspinu** [comment]
@roryk, this should be fixed by now. I am using your file for tests and everything looks good.

**Comment by roryk** [comment]
Thanks Vitalie,

Sorry to be a pain, it looks like there are still some issues. If I edit that file and open up a new block below  the cleanup-files-functions block, like this:

```{r foo}
```

and then move back up into foo and try to add to it, Emacs spins the CPU after displaying: `Marker points into wrong buffer #<marker moves after insertion at 3098>'

Happy to give whatever information would help debugging. Thanks!

**Comment by vspinu** [comment]
I have just fixed that.  I really appreaciate your input. No pain at all.

Earlier today I broke the repo (again)t. Right now everything seems to be working as expected so I am freezing it for a while and moving development to a branch.

**Comment by vspinu** [comment]
Hm. The CPU part is fixed. The "marker in wrong buffer" error is still there :( Will fix this tomorrow. Please open a new issue if you see other problems.
