### ISSUE TITLE
Polymode noweb mode is in LaTeX mode even inside a code chunk

### ISSUE THREAD

**Issue by nrnrnr** [vspinu/polymode#56]
Moving to line 119, column 0 of the attached file puts Emacs into LaTeX mode even though the location is in the middle of a code chunk.

Secret gist at https://gist.github.com/nrnrnr/21376936c5afd4e14ba0

**Comment by vspinu** [comment]
I am pretty sure this is fixed. I have made some improvement on the chunk detection recently.

I cannot reproduce because you haven't provided `poly-noweb+sml`.

**Comment by nrnrnr** [comment]
Oops.  Sorry about that.

````
(defcustom pm-inner/noweb+sml
  (clone pm-inner/noweb :mode 'sml-mode)
  "Noweb innermode for SML"
  :group 'innermodes
  :type 'object)

(defcustom pm-poly/noweb+sml
  (clone pm-poly/noweb :innermode 'pm-inner/noweb+sml)
  "Noweb polymode for SML"
  :group 'polymodes
  :type 'object)

(define-polymode poly-noweb+sml-mode pm-poly/noweb+sml :lighter " PM-SMLnw")
````

**Comment by vspinu** [comment]
I have checked this out and it works as expected. Thanks.
