### ISSUE TITLE
Could poly-noweb mode be ignoring default indent-tabs-mode?

### ISSUE THREAD

**Issue by nrnrnr** [vspinu/polymode#59]
My `.emacs` includes

````
(setq-default indent-tabs-mode nil)
````

I just discovered a few unwanted tabs in a file.  It's pretty clear that the tabs were placed by indentation.  
I don't see anything in the polymode source code that would tell me whether polymode might be using tabs for indentation, but I do see some indentation code.  So I thought I had better check.

**Comment by vspinu** [comment]
Polymode should not interfere with the setting in the local modes. Make  sure that your local modes  or dir-local settings don't overwrite the `indent-tabs-mode`.
