### ISSUE TITLE
polymode backtrace on emacs 25.0.50

### ISSUE THREAD

**Issue by sje30** [vspinu/polymode#62]
Hi Vitalie,

I'm getting errors with emacs 25.0.50 on a mac with polymode.  Do you see this?

```
Debugger entered--Lisp error: (invalid-slot-type pm-hbtchunkmode-auto -head-buffer (or null buffer) "^[ 	]*```[{ 	]*\\w.*$")
  signal(invalid-slot-type (pm-hbtchunkmode-auto -head-buffer (or null buffer) "^[ 	]*```[{ 	]*\\w.*$"))
```

Stephen

**Comment by vspinu** [comment]
Sorry, it took me a while to get emacs 25 installed. I don't see the error in emacs master (aka 25.0.50.1).

**Comment by sje30** [comment]
> Sorry, it took me a while to get emacs 25 installed. I don't see the
> error in emacs master (aka 25.0.50.1).

okay, thanks.  I need to debug further locally.

S

**Comment by vspinu** [comment]
I am closing this as not reproducible. I am permanently on emacs master branch so it's pretty sure some local problem of yours.
