### ISSUE TITLE
Unable to select an entire code chunk

### ISSUE THREAD

**Issue by Choens** [vspinu/polymode#63]
Take the following example chunk, from a .Rmd file.

```{r init, echo=FALSE, results="asis"}

source("config.R")

## Variables ===================================================================
report.year <- 2013

```

Using Emacs 24.3.1 on Windows, I am unable to select the entire code chunk. I can only select one piece at a time. I can select the chunk header row, or the code, or the terminating ``` line. But I can not select more than one of these at a time.

On Ubuntu, using Emacs 24.4.1, I am able to select everything. My init.el is nearly identical across the two system. The Windows box is a work computer. If I can get some free time this afternoon, I can try to upgrade to a newer version of Emacs, but I thought I would post this here to see what you thought.

**Comment by Choens** [comment]
I should also say, I really like polymode. Really terrific idea.

**Comment by vspinu** [comment]
24.3.1 is too old. There have been too many low level changes in emacs since then and I have no time to build workarounds for those given that the package is not stable yet. Selection works perfectly for me on emacs 25 so I am closing this as non-fixable.
