### ISSUE TITLE
Aquamacs ESS and R markdown

### ISSUE THREAD

**Issue by ekstroem** [vspinu/polymode#64]
Hi,

I'm not entirely sure how to make the title completely meaningful so I'll just try to explain my problem. I'm trying to get polymode to work with aquamacs on mac. Did the installation from melpa and the `Markdown PM-Rmd` mode is recognized when I open up the following `test.Rmd` file

    ## Importing data

    ```{r}
    library(readxl)
    indata <- read_excel("original_data/ALLAVer9.xlsx") 
    head(indata)
    summary(indata)
     ```

    ## Descriptive statistics

    ```{r}
    # is.Date(indata$föd.datum)
    ```

However, when I run `M-n e`to export the document I get to choose the output format (not sure if it could be defined in the YAML but that is another question), I select html5 and get the following error
`Cannot open load file: no such file or directory, ess`

The same thing happens if I choose to weave the file with `M-n w`.

Can someone point me in the right direction as to what I'm misssing? 

My `.emacs` (actually the `Preferences.el` file) contains the following

```
(defun rmd-mode ()
  "ESS Markdown mode for rmd files"
  (interactive)
;;  (setq load-path 
;;    (append (list "path/to/polymode/" "path/to/polymode/modes/")
;;        load-path))
  (require 'poly-R)
  (require 'poly-markdown)     
  (poly-markdown+r-mode))

(add-to-list 'auto-mode-alist '("\\.[rR]md\\'" . rmd-mode))
```

Claus

**Comment by vspinu** [comment]
I have just rewriten the weave/exporter ecosystem. Everything should work as expected. 

Your error had probably to do with wrong install of ESS. In any case ESS is not required to run export or weaver. You can `M-n E` or `M-n W` and choose shell only options (no ESS required).
