### ISSUE TITLE
Making chunks limits paragraph limits

### ISSUE THREAD

**Issue by lionel-** [vspinu/polymode#67]
When I'm editing a Rmd document, I often need to eval the chunk of R code I'm working on. `(ess-eval-paragraph)` does not work well for this because the paragraph as defined in ESS overlaps over markdown fences.

So I'm using this to make it work as expected:
```lisp
(when (and (boundp 'polymode-mode) polymode-mode)
  (setq paragraph-start (concat "^```.*\n\\|" paragraph-start)
        paragraph-separate (concat "```.*$\\|" paragraph-separate)))
```
Maybe polymode could automatically adjust paragraphing inside each innermode based on the head and tail chunk regexps.

**Comment by vspinu** [comment]
> Maybe polymode could automatically adjust paragraphing inside each innermode based on the head and tail chunk regexps.

Yes, that's on the todo list. But it's not high priority though because there is an easy workaround - leave one space just after the header and before the tail of the chunk.
