### ISSUE TITLE
Weird consistent crash during C-k inside chunk

### ISSUE THREAD

**Issue by aengelberg** [vspinu/polymode#68]
I have this in my `.emacs`:
```
(require 'polymode)
(add-to-list 'auto-mode-alist '("\\.md" . poly-markdown-mode))
```

Steps to reproduce:
- `C-x C-f` and open new file `newname.md` (starts up new buffer in poly-markdown-mode)
- Type the following text:

        # Section
        
        ```javascript
        {
        }
        ```
        
        a

- `C-x C-s`
- Move cursor to after `{`
- `C-k`
- Emacs crashes

Platform: Ubuntu 14.04
Emacs 24.4.1

**Comment by vspinu** [comment]
I cannot reproduce this. I have added a custom handler for kill-buffer so the kill should work as expected from inside the chunks. Feel free to open this if you still see the problem.

**Comment by elfsternberg** [comment]
Emacs 24.3.1 on Ubuntu 14.04.4, same problem: Go to the end of a code chunk in noweb+javascript mode, press Ctrl-K, immediate SEGFAULT.

I don't have debugging symbols in my Emacs, so pasting the long list of addresses probably wouldn't do much good.

**Comment by vspinu** [comment]
Emacs 24.3.1 seems to be full of problems. I am ocasionaly testing it there but "officially" minimal supported version is 24.4. Please consider upgrading.
