### ISSUE TITLE
R mode does not work with .RnW files

### ISSUE THREAD

**Issue by jabranham** [vspinu/polymode#73]
I used the package like suggested in the readme, and associated .Rnw files. However, when I open one, the LaTeX part works, but when I put <<>>= ... @ then the ... part attempts to call R-mode, but R-mode should be r-mode. So it can't find R-mode and uses fundamental mode instead. 

The rmarkdown (.Rmd) works perfectly, though, which is strange.

**Comment by jabranham** [comment]
I was able to solve this by installing ESS via `sudo apt-get install ess` instead of from MELPA. I'm not really sure why that would change anything, though.

**Comment by vspinu** [comment]
It's probably some interference with the order of initialization. ESS comes with `ess-noweb-mode` which probably was overwriting the your polymode file associations.

**Comment by vspinu** [comment]
Actually, not. After re-reading your comment. You have polymode already working in Rnw. Have no idea then. Glad you solved it.

**Comment by vspinu** [comment]
I think ESS was not loaded or something along those lines. It should not matter if it's `r-mode` or `R-mode`. This is taken  care internally in polymode.
