### ISSUE TITLE
Auto-fill not working in R chunks within Rmd files

### ISSUE THREAD

**Issue by plantarum** [vspinu/polymode#80]
Steps to reproduce:

emacs -Q

Emacs version 24.5.50.2

Run the following elisp code to set up a minimal Emacs package environment with ESS, polymode and helpers. The tar files are downloaded from MELPA. (Sorry, can't upload text files to github?)

    (setq package-enable-at-startup nil)
    (package-initialize t)
    (package-install-file "~/dl/ess-20151016.923.tar")
    (package-install-file "~/dl/polymode-20151013.814.tar")
    (package-install-file "~/dl/markdown-mode-20151011.1256.el")
    (require 'poly-R)
    (require 'poly-markdown)
    (add-to-list 'auto-mode-alist '("\\.Rmd" . poly-markdown+r-mode))

Open an Rmd file with the following contents:

    Example code:

    ```{r}
    ## Example code:
    aggregate(argent[, 2:5], by = list(Transect = argent$Transect, Season = argent$Season), FUN = sum)
    ```

With point at the beginning of `aggregate`, try to fill-paragraph with `M-q`. It works once. Undo the change with `C-/` and try again - with point at the beginning of `aggregate`, nothing happens, and a warning message appears: "Could not find function bounds". Trying with point on the 'b' of `by` results in the entire code line being joined to the comment on the previous line. At this point, the fill-paragraph function doesn't seem to work at all for this buffer.

I looked into the code, and found `fill-paragraph` is advised by `ess-roxy-fill-advise`, but didn't find a solution to the problem after working through that for a while.

If there is a better way to reproduce bugs that involve multiple packages, please let me know!

**Comment by plantarum** [comment]
I found an easier way to reproduce the problem (via emacs.stackexchange), without downloading tarballs. Starting with `emacs -Q`, and assuming ESS, polymode and markdown mode are all installed in via `package.el`, evaluate the following elisp:

    (require 'package)
    (setq package-load-list
          '((ess t)
            (polymode t)
            (markdown-mode t)
	    (julia-mode t))) ;; just a dependency to get ess loaded, not used otherwise
    (package-initialize)

    (require 'ess-site)
    (require 'poly-R)
    (require 'poly-markdown)
    (add-to-list 'auto-mode-alist '("\\.Rmd" . poly-markdown+r-mode))

Then try filling the code in an .Rmd file as described above.

**Comment by vspinu** [comment]
I can reproduce the problem but have no idea where it comes from. The filling code is new in ESS 15.09.

**Comment by vspinu** [comment]
This one was fixed on ESS side, but I have added a generic advice for fill-paragraph to polymode as well.
