### ISSUE TITLE
Poly-Noweb with Coffeescript breaks on "this" operator.

### ISSUE THREAD

**Issue by elfsternberg** [vspinu/polymode#86]
Poly-Noweb with Coffeescript breaks on the "this" operator, which in Coffeescript is an @ symbol.  Convention holds that mutators in Coffeescript classes should end with a singular @ to enable chaining, which conflicts with the innermode terminator as defined in poly-noweb.el.  As this symbol is unlikely to appear in the zero column, the easiest fix is to replace 

                   :tail-reg "^[ \t]*@ *\\( %def .*\\)?$")

with

                   :tail-reg "^@ *\\( %def .*\\)?$")

I don't  believe I've ever seen a noweb file with the innermode terminator anywhere but the zero column.

**Comment by vspinu** [comment]
I am pretty sure this one has been fixed. Please re-open if it wasn't and provide a small example. Thanks.
