### ISSUE TITLE
Emacs init error with polymode 20160228.1703

### ISSUE THREAD

**Issue by drgibbon** [vspinu/polymode#88]
Hello, I just updated to polymode 20160228.1703 from MELPA (on GNU Emacs 24.3.1) and on startup I get the following error;
```
Warning (initialization): An error occurred while loading `/home/user/.emacs':
Symbol's function definition is void: advice-add
```

The relevant polymode section in my ~/.emacs is;
```
(require 'poly-R)
(require 'poly-markdown)
(require 'poly-noweb)
(add-to-list 'auto-mode-alist '("\\.Rnw" . poly-noweb+r-mode))
```
If I comment this out then Emacs loads fine. Maybe something changed with the latest update?

**Comment by drgibbon** [comment]
Strangely enough, I just realised that polymode is still working for Rnw files (with mixtures of LaTeX and R knitr chunks); without any polymode initialisation stuff in ~/.emacs at all!
A bit strange, not sure what to make of it.

**Comment by vspinu** [comment]
Ah, sure. One of the advice-add was not protected. 

Your emacs is too old. I have just added a note to the readme that only emacs 24.4 or higher  are supported. There have been too many changes on EIEIO and advice that supporting earlier versions is a plain pain. I am fixing this but unless you upgrade your emacs you will probably see other problems.

**Comment by drgibbon** [comment]
Ok, probably time to upgrade my old Emacs, thanks :)
