### ISSUE TITLE
Special shell characters need escaping when exporting

### ISSUE THREAD

**Issue by Jehops** [vspinu/polymode#89]
Using polymode-20160229.809, when exporting an Rnw file to DVI/PDF/PS file I see.

```
Exporting latex-->pdf with command:
     latexmk -jobname=bootstrap_paper[exported] -pdf bootstrap_paper[woven].tex
zsh:1: no matches found: -jobname=bootstrap_paper[exported]

```

**Comment by vspinu** [comment]
Thanks for spotting this. I am re-working the weave/exporter framework and some small breaches like this are happening.

**Comment by Jehops** [comment]
The problem returned with MELPA polymode-20160303.1910.

**Comment by vspinu** [comment]
Thanks. Re-fixed. The reason I keep missing this is that it works just fine for me. I don't quite understand why that's the case because the same command fails at emacs shell prompt.

**Comment by Jehops** [comment]
It might be because my shell is set to zsh.  When I changed it to /bin/sh the problem went away.  When I changed it back to zsh the problem returned.  Setting the variable explicit-shell-file-name to /bin/sh didn't make a difference.

**Comment by zou-mono** [comment]
This issue still exists in the latest version.
