### ISSUE TITLE
Saving buffer moves point

### ISSUE THREAD

**Issue by Jehops** [vspinu/polymode#93]
When editing Rnw files with LaTeX and R code, and the point is in an R chunk, saving the buffer moves the point to just after the last R chunk.  This is in MELPA version 20160304.1742, but I think it was introduced a few commits back.

**Comment by vspinu** [comment]
I don't see this. What do you have in `before-save-hook`?

**Comment by vspinu** [comment]
Spoke too soon. If I add `delete-trailing-whitespace` the point indeed jumps to the end of the current chunk. Not current buffer.

**Comment by Jehops** [comment]
I'm still seeing the issue after pull in the commits.  The value of `before-save-hook` is `(time-stamp) `and the value of `after-save-hook` is `(sml/generate-buffer-identification)`.  However, if I set both those variables to `nil `, nothing changes.

**Comment by vspinu** [comment]
What emacs is this?

**Comment by vspinu** [comment]
> However, if I set both those variables to nil, nothing changes.

It depends in which buffer you unset them. You need to be in the base buffer (host mode) because save-buffer operates on base buffer only.

**Comment by Jehops** [comment]
This is the first pretest, version 25.0.90.1.  Indeed, I set the values to `nil` while the point was in LaTeX code.

Stepping through the code, I see the jump happens running `local-write-file-hooks`.  My default value for that hook is `TeX-safe-auto-write`.  Setting the hook to `nil` fixes the issue.

**Comment by vspinu** [comment]
I cannot reproduce even though I have the same hooks in tex part.  It's not completely clear to me why this is happening but the workaround seem to be to save-excurse it. Could you please try it again?

**Comment by Jehops** [comment]
The last commit seems to have solved it.  Thanks.
