### ISSUE TITLE
Conflict with adaptive-wrap mode

### ISSUE THREAD

**Issue by izahn** [vspinu/polymode#99]
Activating polymode appears to prevent `adaptive-wrap-prefix-mode` from working correctly. Here is reproduction guide.

1. Start emacs with `emacs -q`
2. Evaluate these lines to install `adaptive-wrap` and `polymode` and to turn on adaptive-wrap automatically.

```emacs-lisp
(require 'package)
(add-to-list 'package-archives 
             '("melpa" . "http://melpa.milkbox.net/packages/") t)

(package-initialize)
(package-install 'adaptive-wrap)
(package-install 'polymode)

(require 'adaptive-wrap)
(require 'polymode)

(add-hook 'visual-line-mode-hook 'adaptive-wrap-prefix-mode)
(global-visual-line-mode 1)
```
3. Visit a .md file and behold the nice word wrap with indentation. For example, you could download and open https://dss.izahn.com/ista/example.md . Everything looks good, as shown in the screenshot below.
![adaptive_wrap1](https://cloud.githubusercontent.com/assets/321235/15687938/82e75820-2745-11e6-8511-0f6ac9d7ec97.png)

4. Turn on polymode and re-visit the example.md file.
```emacs-lisp
 (add-to-list 'auto-mode-alist '("\\.md" . poly-markdown-mode))
```
Adaptive-wrap no longer wraps correctly, as shown in the screen shot below.
![adaptive_wrap2](https://cloud.githubusercontent.com/assets/321235/15687966/bbc1bd02-2745-11e6-9c3d-192c2700de82.png)

System information: 

GNU Emacs 24.5.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.20.3)

Polymode version 20160520.1829 installed from MELPA.

Other stuff that probably doesn't matter:
```
Important settings:
  value of $LANG: en_US.UTF-8
  locale-coding-system: utf-8-unix

Major mode: Markdown

Minor modes in effect:
  poly-markdown-mode: t
  adaptive-wrap-prefix-mode: t
  tooltip-mode: t
  electric-indent-mode: t
  mouse-wheel-mode: t
  tool-bar-mode: t
  menu-bar-mode: t
  file-name-shadow-mode: t
  global-font-lock-mode: t
  font-lock-mode: t
  blink-cursor-mode: t
  auto-composition-mode: t
  auto-encryption-mode: t
  auto-compression-mode: t
  line-number-mode: t
  global-visual-line-mode: t
  visual-line-mode: t
  transient-mark-mode: t
```

**Comment by vspinu** [comment]
`adaptive-wrap` is using `jit-lock-register` and polymode font-locking is no longer based on jit-lock. 

The fix is probably not dificult but I have to get into the details of it. Will try to fix it asap. 

Thanks for the report.
